export const contractPath = "tooling/effect-build-contract.json";
export const operationRegisterPath = "research/post-0.3/reconciliation/r1/SHIP-DEFER-REJECT.csv";
export const nonOperationRegisterPath = "research/post-0.3/reconciliation/r1/NON-OPERATION-REGISTER.csv";
export const adjudicationPath = "research/post-0.3/freeze/SURFACE-ADJUDICATION.json";
export const publicApiPath = "tooling/public-api.json";
export const sigstoreTrustedRootPath = "tooling/sigstore/trusted_root.json";
export const sigstoreNetworkGuardPath = "scripts/release/deny-network.cjs";

export const npmTrustedPublisher = {
  repository: "mannyc2/effect-build",
  workflow: "release.yml",
  environment: "npm",
  expectedPermissions: ["createPackage"],
  semantics: "expected-npm-11.19.1-trust-record-identity-for-publication-not-live-observation",
};

export const npmRegistryUrl = "https://registry.npmjs.org";
export const npmTrustedPublishClient = { node: "24.14.1", npm: "11.11.0" };

export const npmReleaseTarget = {
  version: "0.6.0",
  presenceAtHandoff: "absent-for-all-admitted-packages",
  expectedDistTagsBeforePublication: [
    { name: "effect-build", tags: { latest: "0.3.0" } },
    {
      name: "effect-build-apple",
      tags: { latest: "0.0.0-reserved.0", reserved: "0.0.0-reserved.0" },
    },
    {
      name: "effect-build-archives",
      tags: { latest: "0.0.0-reserved.0", reserved: "0.0.0-reserved.0" },
    },
    { name: "effect-build-bun", tags: { latest: "0.3.0", reserved: "0.0.0-reserved.0" } },
    { name: "effect-build-deno", tags: { latest: "0.3.0", reserved: "0.0.0-reserved.0" } },
    { name: "effect-build-esbuild", tags: { latest: "0.3.0", reserved: "0.0.0-reserved.0" } },
    {
      name: "effect-build-nfpm",
      tags: { latest: "0.0.0-reserved.0", reserved: "0.0.0-reserved.0" },
    },
    { name: "effect-build-node-sea", tags: { latest: "0.3.0", reserved: "0.0.0-reserved.0" } },
    {
      name: "effect-build-python",
      tags: { latest: "0.0.0-reserved.0", reserved: "0.0.0-reserved.0" },
    },
    {
      name: "effect-build-sbom",
      tags: { latest: "0.0.0-reserved.0", reserved: "0.0.0-reserved.0" },
    },
    {
      name: "effect-build-windows",
      tags: { latest: "0.0.0-reserved.0", reserved: "0.0.0-reserved.0" },
    },
  ],
  expectedLatestBeforePublication: [
    { name: "effect-build", version: "0.3.0" },
    { name: "effect-build-apple", version: "0.0.0-reserved.0" },
    { name: "effect-build-archives", version: "0.0.0-reserved.0" },
    { name: "effect-build-bun", version: "0.3.0" },
    { name: "effect-build-deno", version: "0.3.0" },
    { name: "effect-build-esbuild", version: "0.3.0" },
    { name: "effect-build-nfpm", version: "0.0.0-reserved.0" },
    { name: "effect-build-node-sea", version: "0.3.0" },
    { name: "effect-build-python", version: "0.0.0-reserved.0" },
    { name: "effect-build-sbom", version: "0.0.0-reserved.0" },
    { name: "effect-build-windows", version: "0.0.0-reserved.0" },
  ],
};

const appleCertificationCoordinates = [
  "N-native-mechanics|macos-aarch64",
  "N-native-mechanics|macos-x64",
  "P-signed-bun-app|macos-aarch64",
  "P-signed-bun-app|macos-x64",
  "P-signed-deno-app|macos-aarch64",
  "P-signed-deno-app|macos-x64",
  "P-notarized-stapled-app-private-zip|macos-aarch64",
  "P-notarized-stapled-app-private-zip|macos-x64",
  "P-notarized-stapled-dmg|macos-aarch64",
  "P-notarized-stapled-dmg|macos-x64",
  "P-notarized-stapled-pkg|macos-aarch64",
  "P-notarized-stapled-pkg|macos-x64",
  "G-app|macos-aarch64",
  "G-app|macos-x64",
  "G-dmg|macos-aarch64",
  "G-dmg|macos-x64",
  "G-pkg|macos-aarch64",
  "G-pkg|macos-x64",
  "A0",
  "A1",
  "A2",
  "A3",
  "A4",
  "A5",
  "A6",
  "A7",
  "A8",
  "A9",
];

const appleCoordinatesMatching = (predicate) => appleCertificationCoordinates.filter(predicate);
const appleNativeCoordinates = appleCoordinatesMatching((coordinate) => coordinate.startsWith("N-"));
const appleDistributionCoordinates = appleCoordinatesMatching((coordinate) => coordinate.startsWith("P-"));
const appleCleanHostCoordinates = appleCoordinatesMatching((coordinate) => coordinate.startsWith("G-"));
const appleVerdictCoordinates = appleCoordinatesMatching((coordinate) => coordinate.startsWith("A"));
const appleSignedAppCoordinates = appleCoordinatesMatching((coordinate) => coordinate.startsWith("P-signed-"));
const appleNotarizedCoordinates = appleCoordinatesMatching((coordinate) => coordinate.startsWith("P-notarized-"));
const appleNotarizedAppCoordinates = appleCoordinatesMatching((coordinate) =>
  coordinate.startsWith("P-notarized-stapled-app-")
);
const appleDmgCoordinates = appleCoordinatesMatching((coordinate) =>
  coordinate.startsWith("P-notarized-stapled-dmg|") || coordinate.startsWith("G-dmg|")
);
const applePkgCoordinates = appleCoordinatesMatching((coordinate) =>
  coordinate.startsWith("P-notarized-stapled-pkg|") || coordinate.startsWith("G-pkg|")
);
const appleAppChainCoordinates = appleCoordinatesMatching((coordinate) =>
  coordinate.startsWith("P-notarized-stapled-app-") || coordinate.startsWith("G-app|")
);
const appleTool = (name, capabilityId) => ({ name, capabilityId });
const appleOperationToolLineage = {
  "PROD-APPLE-001": { app: [appleTool("plutil", "plist-lint")] },
  "PROD-APPLE-002": { app: [appleTool("codesign", "developer-id-signing")] },
  "PROD-APPLE-003": { dmg: [appleTool("codesign", "developer-id-signing")] },
  "PROD-APPLE-004": {
    pkg: [
      appleTool("productsign", "installer-signing"),
      appleTool("pkgutil", "package-signature-verification"),
    ],
  },
  "PROD-APPLE-005": {
    dmg: [
      appleTool("codesign", "app-signature-verification"),
      appleTool("hdiutil", "udzo-image"),
    ],
  },
  "PROD-APPLE-006": {
    pkg: [
      appleTool("codesign", "app-signature-verification"),
      appleTool("pkgbuild", "component-package"),
      appleTool("productbuild", "flat-package"),
      appleTool("pkgutil", "payload-verification"),
    ],
  },
  "PROD-APPLE-007": {
    dmg: [
      appleTool("codesign", "signature-verification"),
      appleTool("notarytool", "notarization"),
    ],
    pkg: [
      appleTool("pkgutil", "package-signature-verification"),
      appleTool("notarytool", "notarization"),
    ],
  },
  "PROD-APPLE-008": {
    app: [
      appleTool("codesign", "signature-verification"),
      appleTool("ditto", "archive-transport"),
      appleTool("notarytool", "notarization"),
    ],
  },
  "PROD-APPLE-009": {
    app: [appleTool("notarytool", "notarization")],
    dmg: [appleTool("notarytool", "notarization")],
    pkg: [appleTool("notarytool", "notarization")],
  },
  "PROD-APPLE-010": {
    app: [appleTool("notarytool", "notarization")],
    dmg: [appleTool("notarytool", "notarization")],
    pkg: [appleTool("notarytool", "notarization")],
  },
  "PROD-APPLE-011": {
    app: [
      appleTool("codesign", "signature-verification"),
      appleTool("stapler", "ticket-stapling"),
    ],
  },
  "PROD-APPLE-012": {
    dmg: [
      appleTool("codesign", "signature-verification"),
      appleTool("stapler", "ticket-stapling"),
    ],
    pkg: [
      appleTool("pkgutil", "package-signature-verification"),
      appleTool("stapler", "ticket-stapling"),
    ],
  },
  "PROD-APPLE-013": {
    app: [
      appleTool("spctl", "gatekeeper-assessment"),
      appleTool("codesign", "signature-verification"),
    ],
    dmg: [
      appleTool("spctl", "gatekeeper-assessment"),
      appleTool("codesign", "signature-verification"),
    ],
    pkg: [
      appleTool("spctl", "gatekeeper-assessment"),
      appleTool("pkgutil", "package-signature-verification"),
    ],
  },
};
const npmOidcCertificationArtifactProtocol = "effect-build/npm-oidc-certification-artifact@1";
const appleCertificationIndexProtocol = "effect-build/apple-certification-index@2";

const appleHostedReceiptRunnerSelectors = [
  ["N-native", "macos-aarch64"],
  ["N-native", "macos-x64"],
  ["P-signed-app", "macos-aarch64"],
  ["P-signed-app", "macos-x64"],
  ["P-notarized-product", "macos-aarch64"],
  ["P-notarized-product", "macos-x64"],
  ["G-clean-host", "macos-aarch64"],
  ["G-clean-host", "macos-x64"],
  ["A-verdict", null],
].map(([category, coordinateArchitecture]) => ({
  category,
  coordinateArchitecture,
  status: "unqualified",
  runnerLabel: null,
  platform: null,
  architecture: null,
  image: null,
  runnerEnvironment: null,
}));

const appleHostedActivationInterfaces = {
  protocol: "effect-build/apple-hosted-activation-interfaces@1",
  status: "unconfigured",
  producer: {
    status: "unconfigured",
    bundleProtocol: "effect-build/apple-producer-bundle@1",
    sourceSha: null,
    bundleDigest: null,
  },
  verifier: {
    status: "unconfigured",
    bundleProtocol: "effect-build/apple-clean-host-verifier-bundle@1",
    sourceSha: null,
    bundleDigest: null,
  },
  certificates: {
    status: "unconfigured",
    teamId: null,
    applicationSha1: null,
    installerSha1: null,
  },
  environment: {
    status: "provisioned-policy-only",
    authorityScope: "environment-policy-only-not-credential-or-runner-qualification",
    repository: "mannyc2/effect-build",
    repositoryId: "1331906770",
    repositoryOwnerId: "126291407",
    environmentId: "20977544910",
    name: "apple-certification",
    canAdminsBypass: true,
    reviewer: {
      id: 126291407,
      login: "mannyc2",
      type: "User",
      preventSelfReview: false,
    },
    branchPolicy: {
      name: "main",
      type: "branch",
      deploymentBranchPolicy: {
        customBranchPolicies: true,
        protectedBranches: false,
      },
      exactProtectionRuleTypes: ["branch_policy", "required_reviewers"],
      branchPolicies: [{ name: "main", type: "branch" }],
    },
    secretNames: [],
    variableNames: [],
    oidcSubjectPolicy: {
      use_default: true,
      use_immutable_subject: true,
      sub_claim_prefix: "repo:mannyc2@126291407/effect-build@1331906770",
    },
  },
  credentialLayer: {
    status: "unconfigured",
    type: null,
    environment: "apple-certification",
    secretNames: [],
  },
  journal: {
    status: "unconfigured",
    packageName: "@mannyc1/ts-release",
    packageVersion: null,
    sourceSha: null,
    reusableWorkflowRef: null,
    reusableWorkflowSha: null,
    codecId: null,
  },
  aws: {
    status: "unconfigured",
    accountId: null,
    bucketArn: null,
    region: null,
    roleArn: null,
    prefix: "operation-journal/v1",
    retentionPolicyDigest: null,
    iamPolicyDigest: null,
    bucketPolicyDigest: null,
    oidcTrustPolicyDigest: null,
    oidcJobWorkflowRef: null,
    oidcJobWorkflowSha: null,
  },
  runners: {
    status: "unqualified",
    receiptPins: appleHostedReceiptRunnerSelectors,
  },
  continuation: {
    status: "unconfigured",
    initialDelaySeconds: null,
    pollIntervalSeconds: null,
    maximumPolls: null,
    maximumElapsedSeconds: null,
  },
};
const fakeRegistryLocalQualificationProtocol = "effect-build/fake-registry-local-qualification@2";
const fakeRegistryExactProtectedBodyProtocol =
  "effect-build/fake-registry-exact-protected-body-certification@2";
const fakeRegistryDerivedCandidateCoordinates = new Set([
  "embedded-publish-config-invalid/missing",
  "embedded-publish-config-invalid/additional",
  "embedded-publish-config-invalid/non-canonical",
  "embedded-publish-config-invalid/registry-scoped-auth",
  "adopted-evidence-digest-mismatch/candidate-manifest",
  "adopted-evidence-digest-mismatch/candidate-tarball",
]);

const fakeRegistryExactMutationLedger = [
  ["all-absent-full-convergence", 11, 11],
  ["partial-exact-publication", 8, 8],
  ["exact-bytes-latest-wrong", 0, 0],
  ["target-version-conflicting-bytes", 0, 0],
  ["existing-provenance-invalid/missing", 0, 0],
  ["existing-provenance-invalid/unverifiable", 0, 0],
  ["existing-provenance-invalid/wrong-workflow", 0, 0],
  ["existing-provenance-invalid/wrong-source-sha", 0, 0],
  ["existing-provenance-invalid/wrong-source-oid", 0, 0],
  ["existing-provenance-invalid/duplicate-source-oid", 0, 0],
  ["prior-latest-drift-before-first-mutation", 0, 0],
  ["newer-version-present", 0, 0],
  ["inconclusive-non-404-registry-read", 0, 0],
  ["failure-before-registry-commitment", 1, 0],
  ["response-loss-after-registry-commitment", 11, 11],
  ["response-loss-after-bytes-and-tag-before-valid-provenance", 1, 1],
  ["placeholder-or-reservation-tag-drift/placeholder-latest", 0, 0],
  ["placeholder-or-reservation-tag-drift/placeholder-reserved", 0, 0],
  ["placeholder-or-reservation-tag-drift/reservation-only-latest", 0, 0],
  ["placeholder-or-reservation-tag-drift/reservation-only-reserved", 0, 0],
  ["rolldown-non-placeholder-version", 0, 0],
  ["embedded-publish-config-invalid/missing", 0, 0],
  ["embedded-publish-config-invalid/additional", 0, 0],
  ["embedded-publish-config-invalid/non-canonical", 0, 0],
  ["embedded-publish-config-invalid/registry-scoped-auth", 0, 0],
  ["forbidden-protected-environment/NPM_ID_TOKEN", 0, 0],
  ["forbidden-protected-environment/NPM_TOKEN", 0, 0],
  ["forbidden-protected-environment/NODE_AUTH_TOKEN", 0, 0],
  ["forbidden-protected-environment/SIGSTORE_ID_TOKEN", 0, 0],
  ["post-publish-candidate-mismatch/bytes", 1, 1],
  ["post-publish-candidate-mismatch/integrity", 1, 1],
  ["post-publish-candidate-mismatch/size", 1, 1],
  ["main-advances-before-first-mutation", 0, 0],
  ["registry-drift-after-first-mutation", 1, 1],
  ["main-advances-after-first-mutation", 1, 1],
  ["authority-drift-after-first-mutation", 1, 1],
  ["adopted-evidence-digest-mismatch/candidate-zip", 0, 0],
  ["adopted-evidence-digest-mismatch/candidate-manifest", 0, 0],
  ["adopted-evidence-digest-mismatch/candidate-tarball", 0, 0],
  ["adopted-evidence-digest-mismatch/readiness", 0, 0],
].map(([coordinate, attemptedFakeMutations, committedFakeMutations]) => ({
  coordinate,
  attemptedFakeMutations,
  committedFakeMutations,
  candidateBinding: fakeRegistryDerivedCandidateCoordinates.has(coordinate)
    ? "derived-hostile-candidate"
    : "exact-release-candidate",
}));

export const releaseCertificationPolicy = {
  modes: [
    "prepare-exact-sha",
    "certify-exact-sha",
    "publish-certified-bytes",
  ],
  scope: {
    target: "v0.6.0",
    npmPackages: {
      status: "included",
      packageSource: "publicApiProjection.packages",
      appleApiLibrary: "included-as-effect-build-apple",
      packageCountSource: "releaseCertification.publicAdmission.packageCount",
    },
    credentialBackedAppleArtifacts: {
      status: "deferred",
      certification: "not-run-not-passed",
      releaseGate: "excluded-from-v0.6.0",
      products: ["signed-app", "dmg", "pkg"],
      target: "later-separately-qualified-release",
    },
    awsNotaryJournalEvidence: {
      status: "deferred",
      releaseGate: "excluded-from-v0.6.0",
      applicability: "future-credential-backed-apple-artifact-certification-only",
    },
  },
  npmAdministrativeInventory: {
    status: "not-observed",
    releaseGate: "excluded-from-v0.6.0",
    doesNotProve: [
      "trusted-publisher-admin-inventory",
      "publishing-access-two-factor-and-token-policy",
    ],
  },
  githubArtifactDigest: {
    canonicalAlgorithm: "sha256",
    canonicalPattern: "^sha256:[0-9a-f]{64}$",
    uploadActionBoundary: {
      acceptedPattern: "^[0-9a-f]{64}$",
      normalization: "prefix-sha256-exactly-once",
    },
    restMetadata: "canonical-exact-equality",
    downloadedZip: "sha256-bytes-equal-canonical-suffix",
    rejectedForms: [
      "uppercase-hex",
      "double-prefixed",
      "non-sha256-algorithm",
      "bare-digest-outside-upload-action-boundary",
    ],
  },
  githubArtifactCoordinate: {
    orderedFields: [
      "workflow",
      "sourceSha",
      "runId",
      "runAttempt",
      "artifactId",
      "artifactDigest",
    ],
    fieldFormats: {
      workflow: "exact-repository-workflow-identity",
      sourceSha: "40-lowercase-hex",
      runId: "positive-decimal-string",
      runAttempt: "positive-decimal-string",
      artifactId: "positive-decimal-string",
      artifactDigest: "releaseCertification.githubArtifactDigest",
    },
  },
  candidate: {
    protocol: "effect-build/npm-release-candidate@2",
    manifest: "release-candidate.json",
    artifactName: "npm-release-candidate-<sourceSha>",
    workflowPath: ".github/workflows/release.yml",
    coordinate: "releaseCertification.githubArtifactCoordinate",
    retentionDays: 30,
    packageAdmission: "releaseCertification.publicAdmission",
    contents: "exact-admitted-tarballs-plus-one-manifest",
    repositoryCodeInProtectedConsumer: "forbidden",
    event: "workflow_dispatch",
    tarballInspection: {
      protocol: "effect-build/strict-npm-package-ustar-gzip@1",
      blockBytes: 512,
      allowedTypes: ["regular", "directory"],
      manifestPath: "package/package.json",
      root: "package",
      maximumCompressedBytes: 16777216,
      maximumUnpackedBytes: 67108864,
      maximumEntryBytes: 67108864,
      maximumTotalEntryBytes: 67108864,
      maximumManifestBytes: 1048576,
      maximumEntries: 4096,
      gzip: "single-member-rfc1952-fixed-header-no-optional-fields-exact-deflate-consumption-crc32-isize",
      ustar: "posix-ustar-magic-version-octal-only-checksummed-no-pax-gnu-base256-links-or-specials",
      endMarker: "two-zero-blocks-followed-only-by-whole-zero-padding-blocks",
      members: "unique-safe-package-root-regular-files-and-directories-only",
      protectedProjection: {
        sourcePath: "scripts/release/tar-protocol.mjs",
        sourceBytes: 10554,
        sourceDigest: "sha256:cfd70cee204b5d3559fc79037a69cae5a171f914c2df6f015bd0aa38bb3d626d",
        compressedBytes: 3128,
        encoding: "deflate-raw-base64-data-url-exact-source",
      },
    },
  },
  githubAuthority: {
    identitySource: "npmRegistryBoundary.trustedPublisher",
    repositoryId: "1331906770",
    repositoryOwnerId: "126291407",
    repositoryVisibility: "public",
    readOnlyTransport: {
      apiOrigin: "https://api.github.com",
      apiVersion: "2022-11-28",
      artifactRedirectHostPolicy: {
        suffixes: ["blob.core.windows.net"],
        match: "dot-subdomain-only",
        redirectStatuses: [302],
        maximumRedirects: 1,
      },
      releaseAssetRedirectHostPolicy: {
        hosts: ["release-assets.githubusercontent.com"],
        match: "exact",
        directStatuses: [200],
        redirectStatuses: [302],
        maximumRedirects: 1,
      },
      metadataMaximumBytes: 8388608,
      artifactMaximumBytes: 1073741824,
      requestInactivityTimeoutMilliseconds: 60000,
      metadataTotalTimeoutMilliseconds: 60000,
      artifactTotalTimeoutMilliseconds: 900000,
      authorization: "api-origin-first-request-only-stripped-before-redirect",
      tlsRootPolicy: "node-bundled-root-certificates-only",
      ambientConfiguration: "forbidden-home-gh-config-proxy-and-extra-ca",
    },
    branchPolicy: {
      name: "main",
      type: "branch",
      deploymentBranchPolicy: {
        customBranchPolicies: true,
        protectedBranches: false,
      },
      exactProtectionRuleTypes: ["branch_policy", "required_reviewers"],
    },
    reviewer: {
      id: 126291407,
      login: "mannyc2",
      type: "User",
      preventSelfReview: false,
    },
    oidcSubjectPolicy: {
      use_default: true,
      use_immutable_subject: true,
      sub_claim_prefix: "repo:mannyc2@126291407/effect-build@1331906770",
    },
    expectedEnvironmentSubjectSource: "immutable-id-repository-and-environment",
    authorizationSplit: {
      protectedGithubTokenObservations: [
        "repository-metadata",
        "environment-deployment-policy",
        "branch-policy",
        "oidc-subject-policy",
        "current-main",
        "workflow-blob",
      ],
      administrativeExternalOnly: [
        "repository-secret-name-inventory",
        "repository-variable-name-inventory",
        "environment-secret-name-inventory",
        "environment-variable-name-inventory",
      ],
      runtimeForbiddenEnvironmentSource:
        "releaseCertification.npmOidcCertification.forbiddenEnvironmentNames",
      publishGate: "releaseCertification.readiness exact-three-github-evidence aggregate",
      forbiddenCredentialEscalation: ["personal-access-token", "github-app-token", "administrative-token"],
    },
  },
  dependencyBootstrap: {
    protocol: "effect-build/checkout-dependency-bootstrap@1",
    client: {
      executable: "bun",
      version: "1.3.14",
    },
    lockfile: {
      path: "bun.lock",
      format: "bun-text-lockfile-v1",
      nonWorkspaceIntegrityAlgorithm: "sha512",
      nonWorkspaceIntegrityPattern: "^sha512-[A-Za-z0-9+/]+={0,2}$",
      requirement: "every-non-workspace-package-exact-integrity-required",
    },
    command: {
      arguments: ["install", "--frozen-lockfile", "--ignore-scripts"],
      lifecycleScripts: "forbidden",
    },
    registries: {
      default: "https://registry.npmjs.org",
      scopes: {
        "@jsr": "https://npm.jsr.io",
      },
    },
    environment: {
      home: "fresh-empty-private",
      cache: "fresh-empty-private",
      temporary: "fresh-empty-private",
      configuration: "exact-auth-free-project-npmrc-empty-user-global-npmrc-and-exact-bunfig",
      configurationFiles: {
        projectNpmrc: {
          path: ".npmrc",
          digest: "sha256:82952390ba119c39e2e495c5afdd42a45129f8ce49918f219eca7bcd6549c7d9",
        },
        bunfig: {
          path: "scripts/release/bunfig.release-bootstrap.toml",
          digest: "sha256:e5de342dbde5ef6b7eadaf1bba167f865a6ecf0d35c8d1ffdd0dbb0726d836b3",
        },
      },
      forbidden: "auth-proxy-extra-ca-node-options-and-host-home-config",
    },
    network: "lockfile-resolved-dependency-bootstrap-only",
    evidence: "never-release-evidence",
  },
  provenanceVerification: {
    purpose: "npm-publication-provenance-verification-only",
    status: "implemented",
    module: "scripts/release/sigstore-dsse-verifier.mjs",
    client: { package: "@sigstore/verify", version: "3.1.1" },
    bundleClient: { package: "@sigstore/bundle", version: "4.0.0" },
    protobufClient: { package: "@sigstore/protobuf-specs", version: "0.5.2" },
    runtime: { executable: "node", version: npmTrustedPublishClient.node },
    networkGuard: {
      path: sigstoreNetworkGuardPath,
      bytes: 4379,
      digest: "sha256:acb4f347c8abb4dbc98d138b487b7cf316a3ccbbbf3a2da2108e68e9b343de77",
      strategy: "preload-standard-node-network-api-denial-plus-audited-direct-verifier-closure",
    },
    trustedRoot: {
      path: sigstoreTrustedRootPath,
      mediaType: "application/vnd.dev.sigstore.trustedroot+json;version=0.1",
      bytes: 6787,
      digest: "sha256:6494e21ea73fa7ee769f85f57d5a3e6a08725eae1e38c755fc3517c9e6bc0b66",
      tuf: {
        mirror: "https://tuf-repo-cdn.sigstore.dev",
        target: "trusted_root.json",
        targetsMetadataVersion: 14,
        targetLength: 6787,
        targetSha256: "sha256:6494e21ea73fa7ee769f85f57d5a3e6a08725eae1e38c755fc3517c9e6bc0b66",
        acquisition: {
          retrievedAt: "2026-08-30T15:07:03.000Z",
          cache: "fresh-empty-temporary-directory",
          home: "isolated-empty-directory",
          network: "exact-official-mirror-only",
          evidenceEncoding: "base64-of-exact-retrieved-bytes",
          verificationModule: "scripts/release/verify-sigstore-tuf-provenance.mjs",
          clients: [
            {
              package: "@sigstore/tuf",
              version: "4.0.2",
              integrity: "sha512-TCAzTy0xzdP79EnxSjq9KQ3eaR7+FmudLC6eRKknVKZbV7ZNlGLClAAQb/HMNJ5n2OBNk2GT1tEmU0xuPr+SLQ==",
            },
            {
              package: "tuf-js",
              version: "4.1.0",
              integrity: "sha512-50QV99kCKH5P/Vs4E2Gzp7BopNV+KzTXqWeaxrfu5IQJBOULRsTIS9seSsOVT8ZnGXzCyx55nYWAi4qJzpZKEQ==",
            },
            {
              package: "@tufjs/models",
              version: "4.1.0",
              integrity: "sha512-Y8cK9aggNRsqJVaKUlEYs4s7CvQ1b1ta2DVPyAimb0I2qhzjNk+A+mxvll/klL0RlfuIUei8BF7YWiua4kQqww==",
            },
          ],
          seedRoot: {
            path: "tooling/sigstore/tuf/seed-root-v14.json.base64",
            version: 14,
            expiresAt: "2026-06-22T13:27:01.000Z",
            bytes: 5490,
            digest: "sha256:c8c41ec13f06ccabf5b48541ee2550098b4c7b5349e1d180390c29a7d5c2642c",
            clientSeedsBytes: 19326,
            clientSeedsDigest: "sha256:1300a33af16967e998983b364ab9988cd5c20e94c44e75d642dbeda1dbc255d9",
          },
          metadata: {
            root: {
              path: "tooling/sigstore/tuf/root-v15.json.base64",
              version: 15,
              expiresAt: "2026-11-20T13:58:18.000Z",
              bytes: 5630,
              digest: "sha256:73747011d0857ada15479a16c4cae0f3ed03aac698b523b97e1de314ac9d9ca8",
            },
            timestamp: {
              path: "tooling/sigstore/tuf/timestamp-v769.json.base64",
              version: 769,
              expiresAt: "2026-09-05T19:19:49.000Z",
              bytes: 449,
              digest: "sha256:fa85cf89eeeec634759809a793a6056940f57c47b9fa1da4d095b0f9852e18c4",
            },
            snapshot: {
              path: "tooling/sigstore/tuf/snapshot-v165.json.base64",
              version: 165,
              expiresAt: "2036-05-15T08:09:16.000Z",
              bytes: 1760,
              digest: "sha256:8f784ab614ec62bfdd5f568eb2a2e3011668449ba235ed4eb7befa99f8469933",
            },
            targets: {
              path: "tooling/sigstore/tuf/targets-v14.json.base64",
              version: 14,
              expiresAt: "2036-05-09T09:00:52.000Z",
              bytes: 4942,
              digest: "sha256:6a697f7f8908c8ab26c11786ecb490b54acec97fa8c802e399f065f8a0cc1acd",
            },
          },
          verification:
            "retained-seed-root-rotation-signatures-expiry-versions-descriptors-and-target-bytes-replay",
        },
      },
      verification: "offline-direct-verifier-no-tuf-network-or-cache-fallback",
    },
    bundleMediaType: "application/vnd.dev.sigstore.bundle.v0.3+json",
    certificateIssuer: "https://token.actions.githubusercontent.com",
    certificateIdentityMatch: "exact-anchored-uri-from-contract-release-workflow-identity",
    certificateOids: {
      buildSignerUri: "1.3.6.1.4.1.57264.1.9",
      sourceRepositoryUri: "1.3.6.1.4.1.57264.1.12",
      sourceRepositoryDigest: "1.3.6.1.4.1.57264.1.13",
    },
    ctLogThreshold: 1,
    tlogThreshold: 1,
    minimumTlogEntries: 1,
    maximumBundleBytes: 32768,
    forbiddenEnvironmentSource:
      "releaseCertification.npmOidcCertification.forbiddenEnvironmentNames",
    network: "forbidden-by-preload-guard-and-audited-direct-verifier-closure",
  },
  readiness: {
    protocol: "effect-build/release-readiness@3",
    bundleProtocol: "effect-build/release-readiness-evidence-bundle@3",
    bundleFraming: "protocol-line-u32be-canonical-header-u64be-opaque-payload",
    zipExtraction: {
      protocol: "effect-build/strict-flat-zip@1",
      allowedCompressionMethods: [0, 8],
      allowedGeneralPurposeBitMask: 2056,
      allowedExtraFieldIds: [],
      creatorVersionMadeBy: 813,
      requiredVersionNeeded: 20,
      protectedProjection: {
        sourcePath: "scripts/release/zip-protocol.mjs",
        sourceBytes: 15670,
        sourceDigest: "sha256:5a1428e693256fa78abf7358bbf5477b682e4205489cae2c78ef61fd1c2b48a1",
        compressedBytes: 3810,
        encoding: "deflate-raw-base64-data-url-exact-source",
      },
      maximumArchiveBytes: 67108864,
      maximumEntries: 64,
      maximumNameBytes: 255,
      maximumExtraBytes: 4096,
      maximumMemberCompressedBytes: 16777216,
      maximumMemberUncompressedBytes: 16777216,
      maximumTotalUncompressedBytes: 67108864,
      maximumCompressionRatio: 200,
      dataDescriptor: "required-signed-16-byte-exact-central-correlation-when-bit-3-set",
      topology: "single-disk-zero-comment-no-zip64-no-prefix-trailer-or-record-gaps",
      members: "unique-flat-utf8-regular-files-only",
      encryption: "forbidden",
      crc32: "required-before-admission",
    },
    manifest: "release-readiness.json",
    evidenceBundle: "release-readiness.bin",
    orderedFiles: ["release-readiness.json", "release-readiness.bin"],
    artifactName: "effect-build-v0.6.0-release-readiness",
    workflowPath: ".github/workflows/release-readiness.yml",
    event: "workflow_dispatch",
    coordinate: "releaseCertification.githubArtifactCoordinate",
    retentionDays: 30,
    clockSkewSeconds: 60,
    aggregateMaximumAgeSeconds: 14400,
    dispatch: {
      sourceInput: "source_sha",
      candidateInput: "candidate_reference_json",
      evidenceInputs: [
        { role: "exact-main-ci", input: "exact_main_ci_reference_json" },
        { role: "fake-registry", input: "fake_registry_reference_json" },
        { role: "npm-oidc-certification", input: "npm_oidc_certification_reference_json" },
      ],
      githubInputs: "closed-full-reference-json-downloaded-by-workflow",
    },
    githubAuthentication: {
      currentMain: "git-ref-heads-main-exact-sourceSha",
      runStatus: "completed",
      runConclusion: "success",
      artifactExpired: false,
      artifactDigest: "rest-metadata-and-downloaded-zip-sha256-exact",
    },
    githubRunObservation: {
      fields: [
        "schema",
        "workflow",
        "sourceSha",
        "runId",
        "runAttempt",
        "event",
        "headBranch",
        "status",
        "conclusion",
        "createdAt",
        "updatedAt",
      ],
    },
    terminalReferences: {
      protocol: "effect-build/terminal-reference-builder@1",
      implementation: {
        path: "scripts/release/build-terminal-reference.mjs",
        export: "buildTerminalReference",
        sourceAuthority: "contract-provenance-exact-source-bytes",
      },
      kinds: [
        {
          kind: "candidate",
          type: "githubArtifact",
          referenceShape: "candidate",
          identitySource: "releaseCertification.candidate",
        },
        {
          kind: "readiness",
          type: "githubArtifact",
          referenceShape: "readiness",
          identitySource: "releaseCertification.readiness",
        },
        {
          kind: "exact-main-ci",
          type: "githubRun",
          referenceShape: "githubRun",
          identitySource: "releaseCertification.readiness.evidenceRoles[role=exact-main-ci]",
        },
        {
          kind: "fake-registry",
          type: "githubArtifact",
          referenceShape: "githubArtifact",
          identitySource: "releaseCertification.readiness.evidenceRoles[role=fake-registry]",
        },
        {
          kind: "npm-oidc-certification",
          type: "githubArtifact",
          referenceShape: "githubArtifact",
          identitySource: "releaseCertification.readiness.evidenceRoles[role=npm-oidc-certification]",
        },
      ],
      readinessFreshness: {
        maximumAgeSeconds: 3600,
        maximumValiditySeconds: 3600,
      },
      terminalState: {
        status: "completed",
        conclusion: "success",
      },
      observationTime:
        "after-terminal-run-updated-at-artifact-created-at-and-final-current-main-read",
      artifactExpiration:
        "minimum-of-observedAt-plus-kind-maximumValiditySeconds-and-github-artifact-expires_at",
      artifactPayload: "raw-downloaded-zip-bytes-with-contract-exact-file-set",
      output: "canonical-reference-json-stdout-only",
      credentialOutput: "forbidden",
    },
    directObservation: {
      protocol: "effect-build/release-readiness-direct-observation@1",
      fields: ["schema", "sourceSha", "observedAt", "github", "npm"],
      githubFields: [
        "repository",
        "repositoryId",
        "repositoryOwnerId",
        "visibility",
        "environment",
        "deploymentBranchPolicy",
        "deploymentBranchPolicies",
        "oidcSubjectPolicy",
        "workflowPath",
        "workflowDigest",
        "currentMain",
      ],
      environmentFields: ["name", "protectionRuleTypes", "reviewer", "preventSelfReview"],
      reviewerFields: ["id", "login", "type"],
      branchPolicyFields: ["name", "type"],
      npmFields: ["registry", "targetVersion", "packages"],
      npmPackageFields: ["name", "versions", "distTags", "repository", "placeholder"],
      repositoryFields: ["type", "url"],
      placeholderFields: ["version", "bytes", "sha256", "integrity", "tarballUrl"],
      packageSource: "publicApiProjection.packages plus npmRegistryBoundary.reservation.packages",
      placeholderSource: "npmRegistryBoundary.bootstrap.placeholderLedger",
      targetState: "absent-from-all-public-packages",
      authentication: {
        github: "GITHUB_TOKEN-actions-contents-deployments-read",
        npm: "anonymous-no-auth",
      },
      githubEndpoints: [
        "repository-metadata",
        "environment-metadata-and-protection-rules",
        "environment-deployment-branch-policy",
        "environment-custom-deployment-branch-policies",
        "repository-oidc-subject-policy",
        "workflow-blob-at-source-sha",
        "current-main-immediately-before-and-after-collection",
      ],
      npmChecks: [
        "target-version-absent",
        "expected-latest-exact",
        "repository-identity-exact",
        "placeholder-versions-tags-and-downloaded-bytes-exact",
      ],
    },
    candidate: {
      protocolSource: "releaseCertification.candidate.protocol",
      referenceType: "candidate",
      coordinate: "required-exact",
      workflowSource: "releaseCertification.candidate.workflow",
      artifactNameSource: "releaseCertification.candidate.artifactName",
      maximumAgeSeconds: 604800,
      maximumValiditySeconds: 604800,
    },
    referenceShapes: {
      candidate: [
        "protocol",
        "coordinate",
        "artifactName",
        "manifestDigest",
        "observedAt",
        "expiresAt",
        "bytes",
      ],
      githubRun: [
        "role",
        "type",
        "protocol",
        "workflow",
        "sourceSha",
        "runId",
        "runAttempt",
        "terminal",
        "observedAt",
        "expiresAt",
        "bytes",
        "digest",
      ],
      githubArtifact: [
        "role",
        "type",
        "protocol",
        "coordinate",
        "artifactName",
        "terminal",
        "evidenceObservedAt",
        "observedAt",
        "expiresAt",
        "bytes",
      ],
    },
    evidenceRoles: [
      {
        role: "exact-main-ci",
        type: "githubRun",
        protocol: "effect-build/exact-main-ci-observation@1",
        terminal: "success",
        workflowPath: ".github/workflows/ci.yml",
        event: "push",
        maximumAgeSeconds: 86400,
        maximumValiditySeconds: 172800,
      },
      {
        role: "fake-registry",
        type: "githubArtifact",
        protocol: fakeRegistryExactProtectedBodyProtocol,
        terminal: "success",
        workflowPath: ".github/workflows/release-certification.yml",
        artifactName: "effect-build-v0.6.0-fake-registry-exact-protected-body-certification",
        event: "workflow_dispatch",
        maximumAgeSeconds: 86400,
        maximumValiditySeconds: 172800,
      },
      {
        role: "npm-oidc-certification",
        type: "githubArtifact",
        protocol: npmOidcCertificationArtifactProtocol,
        terminal: "success",
        workflowPath: ".github/workflows/release.yml",
        artifactName: "effect-build-v0.6.0-npm-oidc-certification",
        event: "workflow_dispatch",
        maximumAgeSeconds: 3600,
        maximumValiditySeconds: 14400,
      },
    ],
  },
  finalPublicVerification: {
    protocol: "effect-build/final-public-verification@2",
    workflowPath: ".github/workflows/release-verification.yml",
    event: "workflow_dispatch",
    status: "ready",
    upstreamGateSource: "releaseCertification.readiness",
    artifactDisposition: "allowed-on-terminal-readiness-success",
    permissions: {
      actions: "read",
      contents: "read",
      idToken: "none",
      packages: "anonymous-read",
      repositoryMutation: "forbidden",
    },
    dispatch: {
      sourceInput: "source_sha",
      candidateInput: "candidate_reference_json",
      readinessInput: "readiness_reference_json",
      tagInput: "tag_reference_json",
      releaseInput: "release_reference_json",
    },
    referenceShapes: {
      candidate: ["protocol", "coordinate", "artifactName", "manifestDigest", "observedAt", "expiresAt", "bytes"],
      readiness: ["protocol", "coordinate", "artifactName", "manifestDigest", "observedAt", "expiresAt", "bytes"],
      tag: ["repository", "name", "targetSha", "objectType", "form"],
      release: [
        "repository",
        "releaseId",
        "tagName",
        "targetSha",
        "draft",
        "prerelease",
        "immutable",
        "observedAt",
      ],
    },
    candidate: {
      protocolSource: "releaseCertification.candidate.protocol",
      workflowSource: "releaseCertification.candidate.workflow",
      artifactNameSource: "releaseCertification.candidate.artifactName",
      coordinate: "releaseCertification.githubArtifactCoordinate",
    },
    readiness: {
      protocolSource: "releaseCertification.readiness.protocol",
      workflowSource: "releaseCertification.readiness.workflow",
      artifactNameSource: "releaseCertification.readiness.artifactName",
      coordinate: "releaseCertification.githubArtifactCoordinate",
    },
    tagPolicy: {
      nameSource: "npmRegistryBoundary.publicationAdmission.target.version prefixed with v",
      objectType: "commit",
      form: "lightweight-direct-commit",
      exactTargetSource: "dispatch.source_sha",
      mutation: "forbidden",
    },
    releasePolicy: {
      idFormat: "positive-decimal-string",
      draft: false,
      prerelease: false,
      tagNameSource: "finalPublicVerification.tag",
      targetShaSource: "authenticated-lightweight-tag-ref-only",
      targetCommitishSource: "releaseCertification.githubAuthority.branchPolicy.name-presentation-only",
      assetSource: "candidate ordered package ledger plus candidate manifest",
      immutabilityDecisionSource: "live-operator-admin-preflight-before-draft-and-public-release",
      mutation: "forbidden",
    },
    publicState: {
      npmRegistrySource: "npmRegistryBoundary.registry",
      versionSource: "npmRegistryBoundary.publicationAdmission.target.version",
      packageSource: "publicApiProjection.packages",
      moduleSource: "publicApiProjection.packages package roots and subpaths",
      releaseAssetSource: "candidate ordered package ledger plus releaseCertification.candidate.manifest",
      requiredChecks: [
        "authenticated-current-main-exact-source",
        "authenticated-candidate-coordinate-and-downloaded-bytes",
        "authenticated-readiness-coordinate-and-downloaded-bytes",
        "lightweight-tag-directly-targets-source",
        "public-release-nondraft-nonprerelease-exact-tag-and-canonical-branch-presentation",
        "twelve-release-assets-candidate-exact-by-name-size-digest-and-download",
        "eleven-anonymous-npm-tarballs-candidate-exact-size-sha256-sha512",
        "eleven-latest-tags-exact-version",
        "eleven-sigstore-provenance-subject-workflow-and-source-exact",
        "fresh-node-and-bun-cache-consumer-smoke-all-public-modules",
        "rolldown-reservation-invariants-unchanged",
      ],
    },
    freshness: {
      clockSkewSeconds: 60,
      maximumObservationAgeSeconds: 3600,
    },
    implementation: {
      status: "implemented",
      module: "scripts/release/final-public-verification.mjs",
      contractAuthentication: "exact-generated-bytes",
      githubBoundary: "github-token-read-only-api-no-cross-origin-authorization",
      npmBoundary: "anonymous-registry-read-only-no-preexisting-auth",
      observationFields: {
        npmPackage: ["name", "version", "latest", "bytes", "sha256", "integrity", "tarballUrl"],
        releaseAsset: ["name", "assetId", "bytes", "digest", "apiUrl", "browserDownloadUrl"],
        provenance: ["name", "attestationUrl", "bundleDigest", "subjectDigest", "workflow", "sourceSha"],
        consumerSmoke: ["schema", "version", "node", "bun", "publicModules", "pipelines", "passed"],
        reservation: ["name", "version", "versions", "latest", "reserved", "bytes", "sha256", "integrity"],
      },
      provenance: {
        attestationPath: "/-/npm/v1/attestations/<encoded-name>@<version>",
        predicateType: "https://slsa.dev/provenance/v1",
        payloadType: "application/vnd.in-toto+json",
        statementType: "https://in-toto.io/Statement/v1",
        buildType: "https://slsa-framework.github.io/github-actions-buildtypes/workflow/v1",
        builderId: "https://github.com/actions/runner/github-hosted",
        subjectDigest: "sha512:<128-lowercase-hex>",
        certificateIdentitySource: "releaseCertification.githubAuthority expected release workflow identity",
        certificateIssuerSource: "releaseCertification.provenanceVerification",
        certificateOidSource: "releaseCertification.provenanceVerification",
      },
      consumerSmoke: {
        protocol: "effect-build/final-public-consumer-smoke@1",
        fields: ["schema", "version", "node", "bun", "publicModules", "pipelines", "passed"],
        node: {
          executor: "node",
          command: "node scripts/test-built-consumer.mjs --registry-version <version> --runtime node --json",
          client: "releaseCertification.npmOidcCertification.client",
          cache: "fresh-empty-npm-cache-and-install-root",
          reportFields: ["executor", "version", "npm", "cache", "publicModules", "pipelines", "passed"],
          configurationIsolation:
            "empty-project-user-global-npmrc-explicit-registry-cache-prefix-and-same-child-config-audit-before-and-after-install",
        },
        bun: {
          executor: "bun",
          command: "bun scripts/test-built-consumer.mjs --registry-version <version> --runtime bun --json",
          versionSource: "exactToolEvidenceRegister.tools kind=provider name=bun",
          cache: "fresh-empty-bun-cache-and-install-root",
          reportFields: ["executor", "version", "cache", "publicModules", "pipelines", "passed"],
          configurationIsolation:
            "empty-project-user-global-npmrc-and-bunfig-explicit-registry-cache-prefix-and-same-child-npm-config-audit-before-and-after-install",
        },
        ambientConfiguration:
          "forbidden-auth-proxy-extra-ca-node-options-and-host-home-config-with-fresh-empty-home-cache-prefix-and-install-root",
        moduleSource: "publicApiProjection.packages package roots and subpaths",
        representativePipelines: [
          "esbuild-in-memory-provider-build",
          "artifact-file-finalization-and-adoption",
          "artifact-byte-mutation-rejection",
        ],
      },
      reservation: {
        package: "effect-build-rolldown",
        ledgerSource: "npmRegistryBoundary.bootstrap.placeholderLedger",
        targetVersion: "forbidden",
        exactVersions: "reservation-ledger-version-only",
      },
    },
    receipt: {
      protocol: "effect-build/final-public-release-receipt@2",
      artifactName: "effect-build-v0.6.0-final-public-release",
      retentionDays: 90,
      orderedFiles: ["final-public-release.json"],
      fields: [
        "schema",
        "sourceSha",
        "observedAt",
        "contract",
        "candidate",
        "readiness",
        "tag",
        "release",
        "npmPackages",
        "releaseAssets",
        "provenance",
        "consumerSmoke",
        "reservation",
        "verdict",
      ],
      terminalVerdict: "success",
      externalArchive: "operator-controlled-retention-required",
    },
  },
  npmOidcCertification: {
    client: npmTrustedPublishClient,
    protectedReadOnlyTransport: {
      protocol: "effect-build/protected-release-read-only-transport@1",
      githubPolicySource: "releaseCertification.githubAuthority.readOnlyTransport",
      npmRegistryOriginSource: "npmRegistryBoundary.registry",
      oidcRequest: {
        hostPattern: "^(?:pipelines[a-z0-9-]*|run-actions-[0-9]+-[a-z0-9-]+)\\.actions\\.githubusercontent\\.com$",
        pathPattern:
          "^(?:/[A-Za-z0-9_-]{20,}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/_apis/distributedtask/hubs/[A-Za-z]+/plans/[A-Za-z0-9_-]{20,}/jobs/[A-Za-z0-9_-]{20,}/idtoken|/[0-9]+//idtoken/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
        initialQuery: "api-version=2.0",
        audienceName: "audience",
        audienceValue: "npm:registry.npmjs.org",
        authorization: "actions-id-token-request-token-only",
      },
      oidcIssuer: {
        origin: "https://token.actions.githubusercontent.com",
        discoveryPath: "/.well-known/openid-configuration",
        jwksPath: "/.well-known/jwks",
      },
      request: {
        method: "GET",
        redirects: 0,
        requestInactivityTimeoutMilliseconds: 60000,
        metadataTotalTimeoutMilliseconds: 60000,
        oidcSequenceTotalTimeoutMilliseconds: 180000,
        maximumJsonBytes: 8388608,
        contentType: "application-json-or-json-suffix",
        contentEncoding: "identity-or-absent",
        partialResponses: "forbidden",
        tlsRootPolicy: "node-bundled-root-certificates-only",
        ambientConfiguration: "forbidden-home-curl-git-npm-proxy-extra-ca-and-node-options",
      },
    },
    evidence: {
      artifactProtocol: npmOidcCertificationArtifactProtocol,
      protocols: {
        githubOidcClaims: "effect-build/github-oidc-claims@1",
        npmOidcExchangeAccepted: "effect-build/npm-oidc-exchange-accepted@1",
      },
      artifactName: "effect-build-v0.6.0-npm-oidc-certification",
      retentionDays: 30,
      orderedFiles: [
        "github-oidc-claims.json",
        "npm-oidc-exchange-accepted.json",
      ],
      receiptFieldPolicy: "closed-objects-additional-fields-forbidden",
      receiptSchemas: {
        githubOidcClaims: [
          "schema",
          "sourceSha",
          "candidate",
          "client",
          "observedAt",
          "claims",
          "claimsDigest",
          "jwtValidation",
          "sourceDigests",
          "registryMutation",
          "proves",
          "doesNotProve",
        ],
        npmOidcExchangeAccepted: [
          "schema",
          "sourceSha",
          "candidate",
          "client",
          "observedAt",
          "packages",
          "exchanges",
          "beforeRegistryStateDigest",
          "afterRegistryStateDigest",
          "sourceDigests",
          "registryMutation",
          "proves",
          "doesNotProve",
        ],
        client: ["node", "npm"],
        sourceDigest: ["path", "sha256"],
        exchange: ["name", "accepted", "markerCount"],
        jwtValidation: [
          "alg",
          "kid",
          "iat",
          "nbf",
          "exp",
          "issuerConfigurationDigest",
          "jwksDigest",
          "signingKeyDigest",
          "signatureVerified",
        ],
      },
      githubOidcClaims: {
        orderedClaimFields: [
          "aud",
          "environment",
          "event_name",
          "iss",
          "ref",
          "ref_type",
          "repository",
          "repository_id",
          "repository_owner",
          "repository_owner_id",
          "repository_visibility",
          "run_attempt",
          "run_id",
          "runner_environment",
          "sha",
          "sub",
          "workflow_ref",
          "workflow_sha",
        ],
        staticClaims: {
          aud: "npm:registry.npmjs.org",
          event_name: "workflow_dispatch",
          iss: "https://token.actions.githubusercontent.com",
          ref_type: "branch",
          repository_visibility: "public",
          runner_environment: "github-hosted",
        },
        derivedClaimSources: {
          environment: "releaseCertification.githubAuthority.environment",
          ref: "refs/heads/<releaseCertification.githubAuthority.branchPolicy.name>",
          repository: "releaseCertification.githubAuthority.repository",
          repository_id: "releaseCertification.githubAuthority.repositoryId",
          repository_owner: "releaseCertification.githubAuthority.repositoryOwner",
          repository_owner_id: "releaseCertification.githubAuthority.repositoryOwnerId",
          run_attempt: "current-protected-workflow-run-attempt",
          run_id: "current-protected-workflow-run-id",
          sha: "receipt.sourceSha",
          sub: "releaseCertification.githubAuthority.expectedEnvironmentSubject",
          workflow_ref:
            "<repository>/.github/workflows/<workflow>@refs/heads/<branchPolicy.name>",
          workflow_sha: "receipt.sourceSha",
        },
        claimsDigest: "releaseCertification.githubArtifactDigest-of-canonical-claims-json",
        rawJwtRetention: "forbidden",
        jwtValidation: {
          alg: "RS256",
          kid: "nonempty-nul-free",
          numericDates: "safe-integer-seconds",
          iatPastSkewSeconds: 300,
          iatFutureSkewSeconds: 60,
          nbfFutureSkewSeconds: 60,
          expPastSkewSeconds: 60,
          maximumLifetimeSeconds: 600,
          publicDocumentDigests: "releaseCertification.githubArtifactDigest",
          signatureVerified: true,
        },
      },
      npmOidcExchangeAccepted: {
        packages: "npmRegistryBoundary.publicationAdmission.packages-exact-order",
        exchanges: "exact-one-accepted-true-markerCount-one-entry-per-package-in-package-order",
        registryState:
          "before-and-after-releaseCertification.githubArtifactDigest-of-canonical-registry-state-exactly-equal",
      },
      receiptClaims: {
        githubOidcClaims: {
          proves: ["github-oidc-signature-and-exact-claims-validated-at-observed-time"],
          doesNotProve: ["npm-oidc-exchange", "tarball-upload", "provenance", "publication"],
        },
        npmOidcExchangeAccepted: {
          proves: ["package-specific-npm-oidc-exchange-accepted-at-observed-time", "registry-state-unchanged"],
          doesNotProve: ["tarball-upload", "provenance", "publication"],
        },
      },
      bindings: {
        candidate: "releaseCertification.githubArtifactCoordinate",
        client: "releaseCertification.npmOidcCertification.client",
        sourceDigests: "releaseCertification.npmOidcCertification.sourceDigests",
        registryMutation: false,
        digest: "releaseCertification.githubArtifactDigest",
        observedAt: "rfc3339",
        markerCount: 1,
      },
    },
    forbiddenEnvironmentNames: [
      "NPM_ID_TOKEN",
      "NPM_TOKEN",
      "NODE_AUTH_TOKEN",
      "SIGSTORE_ID_TOKEN",
    ],
    successMarker: "Successfully retrieved and set token",
    successMarkerCardinality: "exactly-one-per-package-in-private-log",
    sourceDigests: [
      {
        path: "npm/lib/commands/publish.js",
        sha256: "ba4afde95ca02334b0d221213907f458c4ba576c1c583b9d73c8ef99924ba26c",
      },
      {
        path: "npm/lib/utils/oidc.js",
        sha256: "d3cdddc81b038ece6394323dfa2e1ec813b186d7965e0aea0cd2b1c39ce97ef9",
      },
      {
        path: "npm/node_modules/libnpmpublish/lib/publish.js",
        sha256: "39b4994968f6699004c0200ae12cadf328c8d838534315c1978672bf3dd15401",
      },
      {
        path: "npm/node_modules/libnpmpublish/lib/provenance.js",
        sha256: "ee9b1bc8e3f636fbaf5138a3e183ce3c6d42bb5dd57ab004578e534dd08da46b",
      },
      {
        path: "npm/node_modules/@sigstore/sign/dist/identity/ci.js",
        sha256: "23e3c7c5799a54f7818b3d8d8f0bf9980b8b61a1f0b39632b941c6fb82aca327",
      },
    ],
    auditedOrdering: [
      "npm-oidc-exchange-before-dry-run-mutation-guard",
      "libnpmpublish-provenance-before-registry-put",
      "sigstore-provider-order-github-request-token-then-environment-token",
    ],
    dryRunClaim: "package-specific-oidc-exchange-accepted-with-zero-registry-mutation",
    forbiddenDryRunClaims: [
      "tarball-upload-certified",
      "provenance-certified",
      "publication-certified",
    ],
  },
  fakeRegistry: {
    localQualification: {
      protocol: fakeRegistryLocalQualificationProtocol,
      workflowPath: ".github/workflows/release-certification.yml",
      artifactName: "effect-build-v0.6.0-fake-registry-local-qualification",
      terminal: "local-qualification",
      retentionDays: 30,
      readinessAdmissible: false,
      proves: [
        "real-purpose-without-readiness-stops-before-first-mutation",
        "sealed-credential-free-exact-purpose-covers-40-state-machine-coordinates",
        "independent-reference-oracle-agrees-with-exact-purpose",
        "npm-oidc-dry-run-body-local-boundaries",
      ],
      doesNotProve: [
        "readiness-admissible-exact-protected-body-certification",
        "readiness-admission",
        "same-candidate-resume-after-readiness-expiry",
        "npm-upload",
        "provenance",
        "publication",
      ],
    },
    exactProtectedBodyCertification: {
      protocol: fakeRegistryExactProtectedBodyProtocol,
      workflowPath: ".github/workflows/release-certification.yml",
      artifactName: "effect-build-v0.6.0-fake-registry-exact-protected-body-certification",
      terminal: "success",
      implementationStatus: "implemented",
      status: "supported",
      gateSource: "releaseCertification.readiness.githubAuthentication",
      artifactDisposition: "required-on-terminal-workflow-success",
      readinessAdmission: "requires-same-source-terminal-success-exact-body-artifact",
      retentionDays: 30,
      orderedFiles: ["fake-registry-exact-protected-body.json"],
      receiptFields: [
        "schema",
        "sourceSha",
        "observedAt",
        "workflow",
        "contractDigest",
        "readinessProtocol",
        "candidate",
        "candidateManifestDigest",
        "coordinates",
        "coordinateCount",
        "claims",
        "doesNotProve",
        "realRegistryMutation",
        "realNpmOrRegistryCredentialsUsed",
        "terminal",
      ],
      coordinateFields: [
        "coordinate",
        "status",
        "attemptedFakeMutations",
        "committedFakeMutations",
        "candidateBinding",
        "candidateArtifactDigest",
        "candidateManifestDigest",
      ],
      coordinateSource: "releaseCertification.fakeRegistry.hypotheticalStateMachine.cases-exact-expanded-order",
      exactMutationLedger: fakeRegistryExactMutationLedger,
      requiredClaims: [
        "exact-protected-reauthorization-and-publisher-bodies-executed-against-stateful-fake-boundaries",
        "all-40-exact-body-case-coordinates-terminal",
        "zero-real-registry-mutation",
      ],
      doesNotProve: [
        "same-candidate-resume-after-readiness-expiry",
        "npm-upload",
        "provenance",
        "publication",
      ],
      certificationPurpose: {
        protocol: "effect-build/fake-registry-exact-protected-body-purpose@2",
        selector: {
          environment: "EFFECT_BUILD_PUBLISH_PURPOSE",
          value: "fake-registry-exact-protected-body-certification",
        },
        transportOnlySelectorValue: "fake-registry-exact-protected-body-real-gate-certification",
        transportOnlyPurpose:
          "sealed-fake-network-executes-real-readiness-gate-without-skipping-or-mutating",
        protectedWorkflowExposure: "forbidden",
        producerWorkflowPath: ".github/workflows/release-certification.yml",
        certificationMode: "publish-certified-bytes",
        instrumentedModes: ["certify-exact-sha", "publish-certified-bytes"],
        skippedStage: "final-readiness-adoption-only",
        sharedBodyStages: [
          "protected-reauthorization",
          "authenticated-contract-adoption",
          "candidate-adoption-and-byte-validation",
          "npm-source-and-environment-authentication",
          "registry-prefix-and-reservation-observation",
          "per-package-main-reauthorization",
          "publish-mutation",
          "exact-byte-latest-and-provenance-verification",
          "terminal-registry-verification",
        ],
        exactEnvironmentFields: [
          "EFFECT_BUILD_FAKE_EXECUTION_ROOT",
          "EFFECT_BUILD_FAKE_NODE",
          "EFFECT_BUILD_FAKE_BOUNDARY",
          "EFFECT_BUILD_FAKE_CONTRACT_PATH",
          "FAKE_RELEASE_STATE",
          "NODE_OPTIONS",
        ],
        executableNames: ["curl", "npm"],
        statePolicy: "one-regular-single-link-json-file-under-exact-execution-root",
        fixtureContractProjection:
          "exact-canonical-generated-contract-with-placeholder-byte-ledger-derived-from-fixture-archives",
        authorityPolicy: "credential-free-fake-boundaries-only-real-authentication-forbidden",
        networkPolicy: "no-real-github-npm-or-oidc-network",
        realPurposeReadinessPolicy: "semantic-final-readiness-required-unconditionally",
        sourceFiles: [
          {
            path: "test/fixtures/release/exact-fake-boundary.sh",
            sha256: "287bad6308ec315e9b24baba6a8b6c52473dc21e94f82cadb3bd85720aa07f28",
          },
          {
            path: "test/fixtures/release/fake-boundary.mjs",
            sha256: "0b24b3163e7e1bb5282088ea35819f67dfd82db954ecc3a74d86af14969b61f9",
          },
          {
            path: "test/fixtures/release/release-state.mjs",
            sha256: "d858fb22cd987c185055a395c58cf0fd7ae646072d389d683c40bb5f18403bee",
          },
          {
            path: "test/fixtures/release/exact-fake-fetch.mjs",
            sha256: "de0b29d9ab95f8e2fd3f167852766bc61d88cdbe6488e913bd36974dcbce0bed",
          },
          {
            path: "test/fixtures/release/make-candidate.mjs",
            sha256: "63b8f8e5c23197ac061c58e4248faa8076368820529b8a48e4a2e04ca406c3df",
          },
          {
            path: "test/fixtures/release/make-fixture-contract.mjs",
            sha256: "17cc8f2f7aa446a0bc5faad0215dbbd948d14b088c9907bcb3796110cffd4419",
          },
          {
            path: "test/fixtures/release/github-artifact-zip.mjs",
            sha256: "f2d59408673713620f7cf7640f10981d17b40111ad1df2f1ba809081977e1505",
          },
          {
            path: "scripts/release/prepare-fake-certification-inputs.mjs",
            sha256: "9087e4d544028e92703021c20c58837b9242cf5c1f2b6e1b61914e7069532c3d",
          },
        ],
      },
    },
    exactProtectedBody: {
      bodies: ["protected-reauthorization", "publisher"],
      realGateSource: "releaseCertification.readiness",
      fakeGateSource: "releaseCertification.fakeRegistry.exactProtectedBodyCertification.certificationPurpose",
      status: "two-purpose-hard-cut",
      realExpected: "require-exact-three-role-readiness-before-first-registry-mutation",
      fakeExpected: "execute-exact-40-coordinate-state-machine-with-no-real-boundary",
      realBlockedMutationCount: 0,
      proves: [
        "real-purpose-readiness-gate-precedes-first-registry-mutation",
        "exact-fake-purpose-executes-shared-protected-bodies-and-state-machine",
      ],
      doesNotProve: [
        "npm-upload",
        "provenance",
        "publication",
      ],
    },
    hypotheticalStateMachine: {
      status: "reference-oracle-only-not-certification",
      testSubject: "independent-oracle-compared-with-exact-protected-body",
      coordinateCount: 40,
      failureInvariant: "no-later-mutation",
      mutationCountAssertion: "required-exact-per-case",
      forbiddenRecoveryCommands: ["repack", "dist-tag", "unpublish", "external-credential"],
      proves: ["algorithmic-convergence-and-fail-closed-state-transitions-at-fake-boundaries"],
      doesNotProve: [
      "exact-protected-body-execution",
      "npm-upload",
        "provenance",
        "publication",
      ],
      cases: [
        { id: "all-absent-full-convergence", expected: "publish-all-eleven" },
        {
          id: "partial-exact-publication",
          expected: "resume-only-missing-within-current-readiness-validity",
        },
        { id: "exact-bytes-latest-wrong", expected: "stop" },
        { id: "target-version-conflicting-bytes", expected: "stop" },
        {
          id: "existing-provenance-invalid",
          variants: [
            "missing",
            "unverifiable",
            "wrong-workflow",
            "wrong-source-sha",
            "wrong-source-oid",
            "duplicate-source-oid",
          ],
          expected: "stop",
        },
        { id: "prior-latest-drift-before-first-mutation", expected: "stop-zero-mutations" },
        { id: "newer-version-present", expected: "stop-zero-mutations" },
        { id: "inconclusive-non-404-registry-read", expected: "stop-zero-mutations" },
        { id: "failure-before-registry-commitment", expected: "stop-zero-mutations" },
        {
          id: "response-loss-after-registry-commitment",
          expected:
            "stop-then-observation-driven-exact-byte-resume-within-current-readiness-validity",
        },
        {
          id: "response-loss-after-bytes-and-tag-before-valid-provenance",
          expected: "stop-before-later-package",
        },
        {
          id: "placeholder-or-reservation-tag-drift",
          variants: ["placeholder-latest", "placeholder-reserved", "reservation-only-latest", "reservation-only-reserved"],
          expected: "stop-zero-mutations",
        },
        { id: "rolldown-non-placeholder-version", expected: "stop-zero-mutations" },
        {
          id: "embedded-publish-config-invalid",
          variants: ["missing", "additional", "non-canonical", "registry-scoped-auth"],
          expected: "stop-zero-mutations",
        },
        {
          id: "forbidden-protected-environment",
          variants: ["NPM_ID_TOKEN", "NPM_TOKEN", "NODE_AUTH_TOKEN", "SIGSTORE_ID_TOKEN"],
          expected: "stop-zero-mutations",
        },
        {
          id: "post-publish-candidate-mismatch",
          variants: ["bytes", "integrity", "size"],
          expected: "stop-before-later-package",
        },
        { id: "main-advances-before-first-mutation", expected: "stop-zero-mutations" },
        { id: "registry-drift-after-first-mutation", expected: "stop-after-one-committed-mutation" },
        { id: "main-advances-after-first-mutation", expected: "stop-after-one-committed-mutation" },
        { id: "authority-drift-after-first-mutation", expected: "stop-after-one-committed-mutation" },
        {
          id: "adopted-evidence-digest-mismatch",
          variants: ["candidate-zip", "candidate-manifest", "candidate-tarball", "readiness"],
          expected: "stop-zero-mutations",
        },
      ],
    },
  },
  apple: {
    workflowPath: ".github/workflows/apple-certification.yml",
    hostedExecution: {
      protocol: "effect-build/apple-hosted-execution@1",
      status: "blocked",
      blockerIds: [
        "released-qualified-ts-release-journal-and-pinned-reusable-workflow",
        "exact-aws-account-bucket-region-role-prefix-and-oidc-job-workflow-ref",
        "frozen-apple-credential-layer-and-secret-name-inventory",
        "bundled-producer-and-clean-host-executor-identities",
        "qualified-arm64-x64-native-and-clean-host-runner-interfaces",
      ],
      artifactDisposition: "forbidden-while-blocked",
      protectedStageIds: ["sign-app", "submit-product", "continue-notary"],
      activationInterfaces: appleHostedActivationInterfaces,
    },
    protocols: {
      request: "effect-build/apple-certification-request@3",
      receipt: "effect-build/apple-certification-receipt@3",
      evidence: "effect-build/apple-certification-evidence@3",
      priorEvidence: "effect-build/apple-certification-prior-evidence@2",
      bundle: "effect-build/apple-certification-bundle@3",
      index: appleCertificationIndexProtocol,
    },
    notaryJournal: {
      protocol: "effect-build-apple/notary-journal@1",
      submissionCodec: "effect-build-apple/notary-journal@1",
    },
    artifact: {
      name: "effect-build-v0.6.0-apple-certification",
      retentionDays: 30,
      orderedFiles: [
        "apple-certification-index.json",
        "effect-build-v0.6.0-apple-certification.bin",
      ],
      attempt: 1,
    },
    productLineage: {
      canonicalDistributionProvider: "bun",
      canonicalDistributionVersion: "1.3.14",
      products: ["app", "dmg", "pkg"],
      denoCoverage: "signed-app-only",
      privateAppTransport: "zip-not-a-product",
      forbiddenProducts: ["public-zip", "clean-host-zip", "macos-node-sea"],
    },
    encoding: {
      canonicalJson: "utf8-nfc-recursive-lexicographic-keys-no-insignificant-whitespace-final-lf",
      digest: "releaseCertification.githubArtifactDigest",
      bundleFraming: "protocol-line-u32be-canonical-header-u64be-opaque-payload",
      bundleHeaderFields: [
        "protocol",
        "sourceSha",
        "candidateCoordinate",
        "workflowCoordinate",
        "receiptProtocol",
        "receiptCount",
        "receiptsDigest",
        "receipts",
        "evidenceProtocol",
        "evidenceEntries",
        "payloadBytes",
        "payloadDigest",
      ],
      evidenceEntryFields: ["id", "protocol", "coordinate", "offset", "bytes", "digest"],
      indexFields: [
        "protocol",
        "sourceSha",
        "candidateCoordinate",
        "workflowCoordinate",
        "bundleProtocol",
        "bundleFile",
        "bundleBytes",
        "bundleDigest",
        "receiptCount",
        "orderedCoordinates",
        "receiptsDigest",
        "payloadBytes",
        "payloadDigest",
        "verdict",
      ],
      terminalVerdict: "success",
      offsetAndByteEncoding: "canonical-nonnegative-decimal-string",
      payloadLayout: "ordered-contiguous-zero-based-no-gaps-no-trailing-bytes",
    },
    scalarFormats: {
      nonEmptyString: "nonempty-nul-free",
      digest: "releaseCertification.githubArtifactDigest",
      sourceSha: "40-lowercase-hex",
      sha1: "40-lowercase-hex",
      teamId: "10-uppercase-alphanumeric",
      nonNegativeDecimal: "canonical-nonnegative-decimal-string",
      positiveDecimal: "canonical-positive-decimal-string",
      timestamp: "rfc3339",
    },
    pairArchitectureOrder: ["macos-aarch64", "macos-x64"],
    cleanHostForbiddenStateIds: [
      "target-signing-identities",
      "notary-profiles",
      "target-bundle-identifiers",
      "target-package-receipts-and-files",
      "prior-target-product-state",
    ],
    certificatePolicy: {
      classByProduct: {
        app: "Developer ID Application",
        dmg: "Developer ID Application",
        pkg: "Developer ID Installer",
      },
      validity: "notBefore-and-notAfter-cover-common-observedAt",
    },
    operationToolLineage: {
      order: "first-executed-distinct-tool",
      componentFields: ["name", "capabilityId"],
      byOperationId: appleOperationToolLineage,
    },
    receiptSchemas: {
      runnerIdentity: ["runnerLabel", "platform", "architecture", "image", "imageVersion", "runnerEnvironment"],
      digestIdentity: ["bytes", "digest"],
      executableIdentity: ["provider", "version", "architecture", "target", "nativeFormat", "bytes", "digest"],
      toolObservation: ["name", "version", "executableDigest", "observationDigest"],
      appleToolObservation: ["name", "version", "executableDigest", "observationDigest", "nativeObservation"],
      operationFact: ["operationId", "operation", "inputDigests", "outputDigests", "toolObservations"],
      pairMember: ["architecture", "artifactIdentity"],
      pairedAppManifest: ["provider", "version", "pairDigest", "members", "operationFacts"],
      treeArtifactIdentity: ["product", "architecture", "totalBytes", "manifestDigest"],
      fileArtifactIdentity: ["product", "architecture", "bytes", "digest"],
      pairIdentity: ["product", "provider", "pairDigest", "members"],
      certificateFacts: ["class", "teamId", "sha1", "notBefore", "notAfter"],
      verifierFacts: ["artifactDigest", "certificateSha1", "operationFacts", "toolObservations"],
      journalReference: [
        "protocol",
        "journalId",
        "submissionId",
        "intentRecordDigest",
        "intentSequence",
        "intentTransaction",
        "intentRereadRecordDigest",
        "submissionRecordDigest",
        "submissionSequence",
        "submissionTransaction",
        "submissionRereadRecordDigest",
        "submissionCodec",
        "submissionBytesDigest",
      ],
      acceptedInfo: ["submissionId", "providerStatus", "observationDigest", "toolObservation"],
      acceptedLog: ["submissionId", "providerStatus", "logDigest", "issueCount", "toolObservation"],
      stapleTicket: [
        "submissionId",
        "submittedKind",
        "submittedBytes",
        "submittedDigest",
        "targetKind",
        "targetIdentityKind",
        "targetBytes",
        "targetDigest",
        "targetArchitecture",
        "ticketDigest",
      ],
      assessment: ["product", "architecture", "accepted", "evidenceDigest", "toolObservations"],
      acquisitionTransportIdentity: ["kind", "bytes", "digest", "extractedProductDigest"],
      quarantineEvidence: ["applied", "propagated", "attributeDigest"],
      hostIdentity: ["image", "imageVersion", "architecture", "uid", "fresh", "forbiddenStateAbsent"],
      userFlowEvidence: ["flow", "orderedSteps", "evidenceDigest"],
      sentinelOrInstallEvidence: ["kind", "evidenceDigest"],
      cleanupEvidence: ["orderedSteps", "complete", "evidenceDigest"],
    },
    receiptSchemaRules: {
      closedObjects: "all-receipt-schema-objects-reject-unknown-fields",
      strings: "nonempty-nul-free",
      digestFields: "all-fields-named-digest-or-ending-Digest-use-scalarFormats.digest",
      byteAndCountFields: ["bytes", "totalBytes", "issueCount"],
      positiveDecimalFields: ["uid", "intentSequence", "submissionSequence"],
      timestamps: ["observedAt", "notBefore", "notAfter"],
      literalTrueFields: ["hardenedRuntime", "secureTimestamp", "accepted", "applied", "propagated", "fresh", "complete"],
      orderedScalarArrays: [
        "dependencies",
        "orderedDependencies",
        "namedClaims",
        "subordinateEvidence",
        "orderedSteps",
        "inputDigests",
        "outputDigests",
        "forbiddenStateAbsent",
      ],
      operationFactPaths: {
        "N-native": ["operationFacts"],
        "P-signed-app": ["pairedAppManifest.operationFacts", "verifierFacts.operationFacts"],
        "P-notarized-product": ["toolObservations"],
        "G-clean-host": [],
        "A-verdict": [],
      },
      notarizedToolObservations: "ordered-operationFact-array",
      nestedToolObservations: "ordered-toolObservation-array",
      pairMembers: "exact-pairArchitectureOrder",
      pairDigest: "sha256-of-canonical-members-bytes",
      providerStatus: "Accepted",
      commonBindings: [
        "sourceSha",
        "candidateCoordinate",
        "workflowCoordinate",
        "producerDigest",
        "verifierDigest",
      ],
      artifactCoordinate: "releaseCertification.githubArtifactCoordinate",
      journalReference: {
        intentReread: "intentRereadRecordDigest-exactly-equals-intentRecordDigest",
        submissionReread: "submissionRereadRecordDigest-exactly-equals-submissionRecordDigest",
        sequence: "submissionSequence-canonical-positive-decimal-greater-than-intentSequence",
        submissionId: "exactly-equal-across-journalReference-acceptedInfo-acceptedLog-stapleTicket",
      },
    },
    operationCoverage: {
      nativeSource:
        "providerOperationRegister.operations provider in bun,deno semantic=compile-executable mechanism=selected-command disposition=mandatory",
      signedApp: ["buildAppBundles", "signApp"],
      notarizedApp: ["signApp", "submitApp", "info", "log", "stapleApp", "assess"],
      notarizedDmg: ["signDiskImage", "createDiskImages", "submit", "info", "log", "stapleFile", "assess"],
      notarizedPkg: ["signInstallerPackage", "buildInstallerPackages", "submit", "info", "log", "stapleFile", "assess"],
      operationOrder: "producerCapabilityRegister.capabilities-register-order",
    },
    coordinateRuleFields: [
      "coordinate",
      "category",
      "architecture",
      "provider",
      "product",
      "artifactIdentitySchema",
      "dependencies",
      "operationIds",
      "fieldValues",
    ],
    coordinateFieldValuePolicy: {
      notarized: ["signedAppDependency"],
      cleanHost: [
        "producerDependency",
        "runnerPlatform",
        "runnerEnvironment",
        "uidFormat",
        "acquisitionTransportKind",
        "quarantinePolicy",
        "userFlow",
        "userFlowSteps",
        "sentinelOrInstallKind",
        "cleanupSteps",
        "cleanupComplete",
      ],
      verdict: ["namedClaims", "orderedDependencies", "subordinateEvidence"],
      other: [],
    },
    coordinates: appleCertificationCoordinates,
    counts: {
      total: appleCertificationCoordinates.length,
      N: appleNativeCoordinates.length,
      P: appleDistributionCoordinates.length,
      G: appleCleanHostCoordinates.length,
      A: appleVerdictCoordinates.length,
    },
    commonReceiptFields: [
      "protocol",
      "coordinate",
      "sourceSha",
      "candidateCoordinate",
      "workflowCoordinate",
      "producerDigest",
      "verifierDigest",
      "observedAt",
      "runnerIdentity",
      "evidenceDigest",
      "dependencies",
      "verdict",
    ],
    receiptFieldPolicy: "closed-tagged-variants-additional-fields-forbidden",
    categories: [
      {
        id: "N-native",
        coordinatePrefix: "N-native-mechanics|",
        count: appleNativeCoordinates.length,
        requiredFields: [
          "architecture",
          "nativeToolObservations",
          "operationFacts",
          "bunExecutableIdentity",
          "denoExecutableIdentity",
        ],
        forbiddenFields: ["certificate", "credential", "journal", "submission"],
      },
      {
        id: "P-signed-app",
        coordinatePrefix: "P-signed-",
        count: appleSignedAppCoordinates.length,
        requiredFields: [
          "architecture",
          "pairedAppManifest",
          "artifactIdentity",
          "certificateFacts",
          "hardenedRuntime",
          "secureTimestamp",
          "verifierFacts",
        ],
        forbiddenFields: ["notary", "journal", "submission"],
      },
      {
        id: "P-notarized-product",
        coordinatePrefix: "P-notarized-",
        count: appleNotarizedCoordinates.length,
        requiredFields: [
          "signedAppDependency",
          "artifactIdentity",
          "pairIdentity",
          "certificateFacts",
          "journalReference",
          "acceptedInfo",
          "acceptedLog",
          "stapleTicket",
          "assessment",
          "toolObservations",
        ],
        forbiddenFields: ["credential", "privateLogBody"],
      },
      {
        id: "G-clean-host",
        coordinatePrefix: "G-",
        count: appleCleanHostCoordinates.length,
        requiredFields: [
          "producerDependency",
          "acquisitionTransportIdentity",
          "extractedProductIdentity",
          "quarantineEvidence",
          "hostIdentity",
          "userFlowEvidence",
          "sentinelOrInstallEvidence",
          "cleanupEvidence",
        ],
        forbiddenFields: ["credential", "signingIdentity", "journal", "submission"],
      },
      {
        id: "A-verdict",
        coordinatePrefix: "A",
        count: appleVerdictCoordinates.length,
        requiredFields: ["namedClaims", "orderedDependencies", "subordinateEvidence"],
        forbiddenFields: ["productOutput", "credential", "submissionOwner"],
      },
    ],
    verdicts: [
      {
        coordinate: "A0",
        dependencies: [
          "R-current-main",
          "exact-main-ci",
          "candidate",
          "contract-public-surface",
          "lockfile",
          "certifier",
          "clean-host-verifier",
          "protocol-identities",
        ],
        claims: ["release-foundation-and-protocol-identity"],
      },
      {
        coordinate: "A1",
        dependencies: appleNativeCoordinates,
        claims: ["both-native-mechanics-and-exact-tool-observations"],
      },
      {
        coordinate: "A2",
        dependencies: appleSignedAppCoordinates,
        claims: ["four-bun-and-deno-signed-apps"],
      },
      {
        coordinate: "A3",
        dependencies: appleAppChainCoordinates,
        claims: ["sign-submit-accept-staple-assess-launch-chain"],
      },
      {
        coordinate: "A4",
        dependencies: appleNotarizedAppCoordinates,
        claims: ["private-zip-projects-to-same-app-manifest", "no-public-zip-coordinate"],
      },
      {
        coordinate: "A5",
        dependencies: appleDmgCoordinates,
        claims: ["paired-dmg-distribution-and-clean-host-use"],
      },
      {
        coordinate: "A6",
        dependencies: applePkgCoordinates,
        claims: ["paired-pkg-distribution-and-clean-host-use"],
      },
      {
        coordinate: "A7",
        dependencies: appleNotarizedCoordinates,
        subordinateEvidence: [
          "accepted-both-architectures",
          "pending-both-architectures",
          "rejected-both-architectures",
          "info-and-log",
          "fresh-runner-resume",
          "service-failure",
          "interruption",
          "pre-ack-unknown-outcome",
        ],
        claims: ["notary-outcomes-and-no-blind-resubmission"],
      },
      {
        coordinate: "A8",
        dependencies: appleDistributionCoordinates,
        claims: [
          "certificate-class-team-fingerprint-validity",
          "distinct-application-and-installer-identities",
          "both-credential-layer-redaction-tests",
          "selected-live-notary-type",
          "protected-job-allowlist",
        ],
      },
      {
        coordinate: "A9",
        dependencies: [
          ...appleNativeCoordinates,
          ...appleDistributionCoordinates,
          ...appleCleanHostCoordinates,
          ...appleVerdictCoordinates.slice(0, -1),
        ],
        claims: [
          "exact-cross-links",
          "immutable-inputs",
          "newly-created-outputs",
          "no-duplicates",
          "complete-finalization",
        ],
      },
    ],
  },
};

export const npmPlaceholderLedger = [
  {
    name: "effect-build-apple",
    version: "0.0.0-reserved.0",
    bytes: 334,
    sha256: "07c5d7377a5ca1e741af7eda9e5c2743b6587d60014abb1f8c99bdf4bc9f3b3b",
    integrity: "sha512-T2F2RYz0N9Me48SDs8BEvbVeifxhElcVEvmwMd9zRyPJr9JxcTpRFM5CRasCGyExXYBsqobcn5d2CU22v110FQ==",
    bootstrapTags: { reserved: "0.0.0-reserved.0", latest: "0.0.0-reserved.0" },
  },
  {
    name: "effect-build-archives",
    version: "0.0.0-reserved.0",
    bytes: 334,
    sha256: "492062edd992a7a2942c095f0d6cd54c19f26dca1d1ac96a77f389f8dcf8872f",
    integrity: "sha512-9v/xjMJVBw3hzK0onHwR7m7tnL5YnUnOeIoxzuanAZ1v3v/7CUcMiqJKRFqt+5D4DUBn5XWUb1lnV6lYiAMnBQ==",
    bootstrapTags: { reserved: "0.0.0-reserved.0", latest: "0.0.0-reserved.0" },
  },
  {
    name: "effect-build-nfpm",
    version: "0.0.0-reserved.0",
    bytes: 332,
    sha256: "10ffdcf4a5dd69305bd6f9055b3022ef7290416879786236b4cd7d74c6f887da",
    integrity: "sha512-/TKk/e7Ng68RBNusrUpIreYFUvebu8/wERoZLUAmyVB7CTVxs2JfZFmxeIjedDSQqKplOoVW9QPyqnhIUcIXhQ==",
    bootstrapTags: { reserved: "0.0.0-reserved.0", latest: "0.0.0-reserved.0" },
  },
  {
    name: "effect-build-python",
    version: "0.0.0-reserved.0",
    bytes: 334,
    sha256: "a14369ae0eeb3fc17a020267c8887596a3879590ed4f51da8f41ed4c14bfd394",
    integrity: "sha512-3B6GEFCN9ixneGkIMGky4uE71TvT1iTyJVTkFNbtbZWRd+/TBAIKuyu8AgdbL0qS7sSGL70jM6ehiDEr4Z6UiQ==",
    bootstrapTags: { reserved: "0.0.0-reserved.0", latest: "0.0.0-reserved.0" },
  },
  {
    name: "effect-build-rolldown",
    version: "0.0.0-reserved.0",
    bytes: 334,
    sha256: "eda4638f7eaab55dede0ee5d34954efb88786a645396d91a2a9b04175fb103ff",
    integrity: "sha512-mkI+ekPBY2Y6CyEqXRjnHB2F7RWxn6nTcXuL4C+KoIXL5BFvUu73JY9/JWqGIHLlLdvy4wPm0vnlNIg77KxdAg==",
    bootstrapTags: { reserved: "0.0.0-reserved.0", latest: "0.0.0-reserved.0" },
  },
  {
    name: "effect-build-sbom",
    version: "0.0.0-reserved.0",
    bytes: 333,
    sha256: "5b463d54484692d39c70ddd5feb804ce3e8af03b4b7793da3e7fca8bb1fa773d",
    integrity: "sha512-BjY7ar/5gx2QGasd4mjm1UPKTMws4AY6b4OmqZRJg4dyd4WUap/R68sGMfHXgbyOGiyTiClEuvwPWfa6KrdhuA==",
    bootstrapTags: { reserved: "0.0.0-reserved.0", latest: "0.0.0-reserved.0" },
  },
  {
    name: "effect-build-windows",
    version: "0.0.0-reserved.0",
    bytes: 335,
    sha256: "2743a73f902e3ddc4fcf35ed7b902a79766f5b1ccbbfa80bb5588eeede2c2289",
    integrity: "sha512-s5zCwCD1hhO2+O8LniXoJjELfSnolJhxdDbQYZrwS9T82E6tclUy3yWikXW1XduYYvKxz+WThwvfHhMVQ7TX1A==",
    bootstrapTags: { reserved: "0.0.0-reserved.0", latest: "0.0.0-reserved.0" },
  },
];

export const npmRegistryBootstrap = {
  purpose: "namespace-and-trusted-publisher-bootstrap-only",
  architectureEvidence: false,
  placeholderVersion: "0.0.0-reserved.0",
  placeholderTag: "reserved",
  establishedPackages: [
    "effect-build",
    "effect-build-bun",
    "effect-build-deno",
    "effect-build-esbuild",
    "effect-build-node-sea",
  ],
  placeholderAtHandoffPackages: npmPlaceholderLedger.map(({ name }) => name),
  placeholderLedger: npmPlaceholderLedger,
};

export const expectedDispositionCounts = {
  mandatory: 5,
  "positive-proof-gated": 22,
  "conditional-private": 27,
  rejected: 11,
  superseded: 2,
};

export const exactToolEvidenceRegister = [
  {
    id: "EVIDENCE-BUN",
    kind: "provider",
    name: "bun",
    version: "1.3.14",
    executableBindings: ["EFFECT_BUILD_BUN", "EFFECT_BUILD_BUN_BIN"],
    evidenceCells: [
      "host-native",
      "macos-x64",
      "macos-aarch64",
      "linux-x64-gnu",
      "linux-x64-musl",
      "linux-aarch64-gnu",
      "windows-x64",
    ],
  },
  {
    id: "EVIDENCE-DENO",
    kind: "provider",
    name: "deno",
    version: "2.9.5",
    executableBindings: ["EFFECT_BUILD_DENO", "EFFECT_BUILD_DENO_BIN"],
    evidenceCells: [
      "host-native",
      "macos-x64",
      "macos-aarch64",
      "linux-x64-gnu",
      "linux-aarch64-gnu",
      "windows-x64",
      "windows-aarch64",
    ],
  },
  {
    id: "EVIDENCE-NODE-SEA",
    kind: "provider",
    name: "node",
    version: "26.7.0",
    executableBindings: ["EFFECT_BUILD_NODE"],
    evidenceCells: ["linux-x64-gnu"],
  },
  {
    id: "EVIDENCE-UV",
    kind: "producer",
    name: "uv",
    version: "0.12.0",
    executableBindings: ["EFFECT_BUILD_UV_BIN"],
    evidenceCells: ["uv-build", "poetry-core"],
  },
  {
    id: "EVIDENCE-NFPM",
    kind: "producer",
    name: "nfpm",
    version: "2.47.0",
    executableBindings: ["EFFECT_BUILD_NFPM_BIN"],
    evidenceCells: ["deb", "rpm", "apk", "archlinux", "msix"],
  },
  {
    id: "EVIDENCE-SYFT",
    kind: "producer",
    name: "syft",
    version: "1.50.0",
    executableBindings: ["EFFECT_BUILD_SYFT_BIN"],
    evidenceCells: ["spdx-json", "cyclonedx-json"],
  },
];

export const mandatoryOperationIds = new Set([
  "CAN-BUN-012",
  "CAN-DENO-010",
  "CAN-ESB-001",
  "CAN-ESB-011",
  "CAN-NODE-001",
]);

export const supersededOperationIds = new Set(["CAN-NODE-002", "CAN-NODE-003"]);

export const denoPrivateOperationIds = [
  "CAN-DENO-001",
  "CAN-DENO-002",
  "CAN-DENO-003",
  "CAN-DENO-004",
  "CAN-DENO-005",
  "CAN-DENO-006",
  "CAN-DENO-011",
];

export const rolldownRejectedOperationIds = ["CAN-ROL-021"];

export const operationTargets = Object.fromEntries([
  ["CAN-BUN-001", "Transpiler", "make"],
  ["CAN-BUN-002", "Transpiler", "transform"],
  ["CAN-BUN-003", "Transpiler", "transformSync"],
  ["CAN-BUN-004", "Transpiler", "scan"],
  ["CAN-BUN-005", "Transpiler", "scanImports"],
  ["CAN-BUN-006", "Build", "build"],
  ["CAN-BUN-007", "Build", "buildToDirectory"],
  ["CAN-BUN-008", "Build", "build"],
  ["CAN-BUN-009", "Build", "buildToDirectory"],
  ["CAN-BUN-010", "Watch", "watch"],
  ["CAN-BUN-011", "CompileExecutable", "compileExecutableDirect"],
  ["CAN-BUN-012", "CompileExecutable", "compileExecutable"],
  ["CAN-DENO-001", "Bundle", "memory"],
  ["CAN-DENO-002", "Bundle", "direct"],
  ["CAN-DENO-003", "Bundle", "stdout"],
  ["CAN-DENO-004", "Bundle", "direct"],
  ["CAN-DENO-005", "Bundle", "watch"],
  ["CAN-DENO-006", "Bundle", "declarations"],
  ["CAN-DENO-007", "Transpile", "transpile"],
  ["CAN-DENO-008", "Transpile", "transpileToDirectory"],
  ["CAN-DENO-009", "Transpile", "emitDeclarations"],
  ["CAN-DENO-010", "CompileExecutable", "compileExecutable"],
  ["CAN-DENO-011", "CompileWatch", "watch"],
  ["CAN-ESB-001", "Build", "build"],
  ["CAN-ESB-002", "BuildToDirectory", "buildToDirectory"],
  ["CAN-ESB-003", "Transform", "transform"],
  ["CAN-ESB-004", "AnalyzeMetafile", "analyzeMetafile"],
  ["CAN-ESB-005", "FormatMessages", "formatMessages"],
  ["CAN-ESB-011", "Context", "make"],
  ["CAN-ESB-012", "ContextToDirectory", "make"],
  ["CAN-ESB-015", "Build", "build"],
  ["CAN-ESB-016", "BuildToDirectory", "buildToDirectory"],
  ["CAN-ESB-017", "Watch", "watch"],
  ["CAN-ESB-018", "Serve", "serve"],
  ["CAN-NODE-001", "AssembleExecutable", "assembleDirect"],
  ["CAN-ROL-001", "Build", "make"],
  ["CAN-ROL-002", "Build", "generateScoped"],
  ["CAN-ROL-003", "Build", "writeScoped"],
  ["CAN-ROL-005", "Build", "generate"],
  ["CAN-ROL-006", "Build", "write"],
  ["CAN-ROL-007", "Watch", "direct"],
  ["CAN-ROL-008", "Watch", "skipWrite"],
  ["CAN-ROL-010", "Bundle", "bundle"],
  ["CAN-ROL-011", "BundleToDirectory", "bundleToDirectory"],
  ["CAN-ROL-012", "Watch", "watch"],
  ["CAN-ROL-013", "Transform", "transform"],
  ["CAN-ROL-014", "Parse", "parse"],
  ["CAN-ROL-015", "Minify", "minify"],
  ["CAN-ROL-016", "Resolve", "make"],
  ["CAN-ROL-017", "Scan", "scan"],
  ["CAN-ROL-018A", "DevEngine", "makeMemory"],
  ["CAN-ROL-018B", "DevEngine", "makeToDirectory"],
  ["CAN-ROL-020", "Declaration", "emit"],
  ["CAN-ROL-022", "Config", "load"],
].map(([id, module, exportName]) => [id, { module, exportName }]));

export const coreCapabilityRegister = [
  {
    id: "CORE-ARTIFACT-IDENTITY",
    module: "Artifact",
    visibility: "public",
    owns: ["logical-name", "digest", "immutable-file", "immutable-tree", "immutable-executable"],
  },
  {
    id: "CORE-BORROWED-OUTPUT",
    module: "Author/BorrowedOutput",
    visibility: "public",
    owns: ["scoped-file-observation", "scoped-tree-observation", "interruption-safe-cleanup"],
  },
  {
    id: "CORE-FINALIZE-FILE",
    module: "Author/File",
    visibility: "public",
    owns: [
      "same-parent-stage",
      "revalidation",
      "atomic-no-replace-file-commit",
      "undelivered-commit-rollback",
      "verified-byte-consumption",
    ],
  },
  {
    id: "CORE-FINALIZE-TREE",
    module: "Author/Tree",
    visibility: "public",
    owns: [
      "same-parent-stage",
      "revalidation",
      "process-local-destination-claim",
      "precommit-destination-rejection",
      "atomic-tree-rename",
      "undelivered-commit-rollback",
      "committed-file-projection",
      "verified-tree-consumption",
    ],
  },
  {
    id: "CORE-FINALIZE-EXECUTABLE",
    module: "Author/Executable",
    visibility: "public",
    owns: [
      "same-parent-stage",
      "native-inspection",
      "revalidation",
      "atomic-no-replace-executable-commit",
      "undelivered-commit-rollback",
    ],
  },
  {
    id: "CORE-SELECTED-TOOL",
    module: "Author/Tool",
    visibility: "public",
    owns: ["deterministic-selection", "content-identity", "authentication", "launch-reauthentication"],
  },
  {
    id: "CORE-MATRIX",
    module: "Matrix",
    visibility: "public",
    owns: ["explicit-coordinate-identity", "bounded-matrix-execution"],
  },
  {
    id: "CORE-SYSTEM-TARGET",
    module: "SystemTarget",
    visibility: "public",
    owns: ["artifact-target-identity"],
  },
];

/** Test/evidence-bearing implementations for conditional non-operation rows. */
export const privateSupportRegister = [
  {
    id: "PRIVATE-APPLE-NOTARY-SUBMISSION",
    atomIds: [],
    package: "effect-build-apple",
    module: "internal/NotarySubmission",
    path: "packages/effect-build-apple/src/internal/NotarySubmission.ts",
    exports: ["makeSubmissionEngine"],
    visibility: "private",
  },
  {
    id: "PRIVATE-APPLE-NOTARY-JOURNAL-CODEC",
    atomIds: [],
    package: "effect-build-apple",
    module: "internal/NotaryJournalCodec",
    path: "packages/effect-build-apple/src/internal/NotaryJournalCodec.ts",
    exports: [
      "notaryJournalCodecId",
      "encodeNotaryJournalValue",
      "decodeNotaryJournalValue",
      "submissionReferenceFromSubmission",
    ],
    visibility: "private",
  },
  {
    id: "PRIVATE-APPLE-NOTARY-REJECTION-FIXTURE",
    atomIds: [],
    package: "effect-build-apple",
    module: "internal/NotaryRejectionFixture",
    path: "packages/effect-build-apple/src/internal/NotaryRejectionFixture.ts",
    exports: ["Submitter", "submitOnce", "layer"],
    visibility: "private",
  },
  {
    id: "PRIVATE-NODE-SEA-MODES",
    atomIds: ["S05.1", "S06.1", "S07.1"],
    package: "effect-build-node-sea",
    module: "internal/AssembleModes",
    path: "packages/effect-build-node-sea/src/internal/AssembleModes.ts",
    exports: ["assembleDirect"],
    visibility: "private",
  },
];

const finalized = (kind) => ({
  mode: "canonical-finalizing",
  artifactKind: kind,
  returnsDurableArtifact: true,
});

const nativeResult = {
  mode: "provider-native-result",
  artifactKind: null,
  returnsDurableArtifact: false,
};

export const producerCapabilityRegister = [
  {
    id: "PROD-ARCHIVES-001",
    family: "archives",
    package: "effect-build-archives",
    module: "Archive",
    exports: ["archive"],
    visibility: "public",
    finalization: finalized("file"),
  },
  {
    id: "PROD-ARCHIVES-002",
    family: "archives",
    package: "effect-build-archives",
    module: "SourceArchive",
    exports: ["sourceArchive"],
    visibility: "public",
    finalization: finalized("file"),
  },
  {
    id: "PROD-PYTHON-001",
    family: "python",
    package: "effect-build-python",
    module: "Build",
    exports: ["build"],
    visibility: "public",
    finalization: finalized("file-set"),
  },
  {
    id: "PROD-NFPM-001",
    family: "nfpm",
    package: "effect-build-nfpm",
    module: "Package",
    exports: ["buildPackage", "buildDeb", "buildRpm", "buildApk", "buildArchLinux", "buildMsix"],
    visibility: "public",
    finalization: finalized("file"),
  },
  {
    id: "PROD-APPLE-001",
    family: "apple",
    package: "effect-build-apple",
    module: "AppBundle",
    exports: ["buildAppBundles"],
    visibility: "public",
    finalization: finalized("tree-set"),
  },
  {
    id: "PROD-APPLE-002",
    family: "apple",
    package: "effect-build-apple",
    module: "CodeSign",
    exports: ["signApp"],
    visibility: "public",
    finalization: finalized("tree"),
  },
  {
    id: "PROD-APPLE-003",
    family: "apple",
    package: "effect-build-apple",
    module: "CodeSign",
    exports: ["signDiskImage"],
    visibility: "public",
    finalization: finalized("file"),
  },
  {
    id: "PROD-APPLE-004",
    family: "apple",
    package: "effect-build-apple",
    module: "CodeSign",
    exports: ["signInstallerPackage"],
    visibility: "public",
    finalization: finalized("file"),
  },
  {
    id: "PROD-APPLE-005",
    family: "apple",
    package: "effect-build-apple",
    module: "DiskImage",
    exports: ["createDiskImages"],
    visibility: "public",
    finalization: finalized("file-set"),
  },
  {
    id: "PROD-APPLE-006",
    family: "apple",
    package: "effect-build-apple",
    module: "InstallerPackage",
    exports: ["buildInstallerPackages"],
    visibility: "public",
    finalization: finalized("file-set"),
  },
  {
    id: "PROD-APPLE-007",
    family: "apple",
    package: "effect-build-apple",
    module: "Notary",
    exports: ["submit"],
    visibility: "public",
    finalization: nativeResult,
  },
  {
    id: "PROD-APPLE-008",
    family: "apple",
    package: "effect-build-apple",
    module: "Notary",
    exports: ["submitApp"],
    visibility: "public",
    finalization: nativeResult,
  },
  {
    id: "PROD-APPLE-009",
    family: "apple",
    package: "effect-build-apple",
    module: "Notary",
    exports: ["info"],
    visibility: "public",
    finalization: nativeResult,
  },
  {
    id: "PROD-APPLE-010",
    family: "apple",
    package: "effect-build-apple",
    module: "Notary",
    exports: ["log"],
    visibility: "public",
    finalization: nativeResult,
  },
  {
    id: "PROD-APPLE-011",
    family: "apple",
    package: "effect-build-apple",
    module: "Staple",
    exports: ["stapleApp"],
    visibility: "public",
    finalization: finalized("tree"),
  },
  {
    id: "PROD-APPLE-012",
    family: "apple",
    package: "effect-build-apple",
    module: "Staple",
    exports: ["stapleFile"],
    visibility: "public",
    finalization: finalized("file"),
  },
  {
    id: "PROD-APPLE-013",
    family: "apple",
    package: "effect-build-apple",
    module: "Assess",
    exports: ["assess"],
    visibility: "public",
    finalization: nativeResult,
  },
  {
    id: "PROD-WINDOWS-001",
    family: "windows",
    package: "effect-build-windows",
    module: "SignMsix",
    exports: ["signMsix"],
    visibility: "public",
    finalization: finalized("file"),
  },
  {
    id: "PROD-SBOM-001",
    family: "sbom",
    package: "effect-build-sbom",
    module: "Generate",
    exports: ["generate", "generateSpdxJson", "generateCycloneDxJson"],
    visibility: "public",
    finalization: finalized("file"),
  },
];

const appleCapabilityIds = producerCapabilityRegister
  .filter((entry) => entry.family === "apple")
  .map((entry) => entry.id);

export const fixedPublicSurface = {
  "effect-build": {
    rootNamespaces: ["Artifact", "BorrowedOutput", "Executable", "File", "Matrix", "SystemTarget", "Tool", "Tree"],
    subpaths: {
      "./Artifact": ["CORE-ARTIFACT-IDENTITY"],
      "./Author/BorrowedOutput": ["CORE-BORROWED-OUTPUT"],
      "./Author/Executable": ["CORE-FINALIZE-EXECUTABLE"],
      "./Author/File": ["CORE-FINALIZE-FILE"],
      "./Author/Tool": ["CORE-SELECTED-TOOL"],
      "./Author/Tree": ["CORE-FINALIZE-TREE"],
      "./Matrix": ["CORE-MATRIX"],
      "./SystemTarget": ["CORE-SYSTEM-TARGET"],
    },
  },
  "effect-build-apple": {
    rootNamespaces: ["AppBundle", "Assess", "CodeSign", "DiskImage", "InstallerPackage", "Model", "Notary", "Staple"],
    subpaths: {
      "./AppBundle": ["PROD-APPLE-001"],
      "./Assess": ["PROD-APPLE-013"],
      "./CodeSign": ["PROD-APPLE-002", "PROD-APPLE-003", "PROD-APPLE-004"],
      "./DiskImage": ["PROD-APPLE-005"],
      "./InstallerPackage": ["PROD-APPLE-006"],
      "./Model": appleCapabilityIds,
      "./Notary": ["PROD-APPLE-007", "PROD-APPLE-008", "PROD-APPLE-009", "PROD-APPLE-010"],
      "./Staple": ["PROD-APPLE-011", "PROD-APPLE-012"],
    },
  },
  "effect-build-archives": {
    rootNamespaces: ["Archive", "ArchiveError", "Model", "SourceArchive"],
    subpaths: {
      "./Archive": ["PROD-ARCHIVES-001"],
      "./ArchiveError": ["PROD-ARCHIVES-001", "PROD-ARCHIVES-002"],
      "./Model": ["PROD-ARCHIVES-001", "PROD-ARCHIVES-002"],
      "./SourceArchive": ["PROD-ARCHIVES-002"],
    },
  },
  "effect-build-nfpm": {
    rootNamespaces: ["NfpmConfigurationRejected", "Package"],
    subpaths: { "./Package": ["PROD-NFPM-001"] },
  },
  "effect-build-python": {
    rootNamespaces: ["Build", "PythonBuildError"],
    subpaths: {
      "./Build": ["PROD-PYTHON-001"],
      "./PythonBuildError": ["PROD-PYTHON-001"],
    },
  },
  "effect-build-sbom": {
    rootNamespaces: ["Generate"],
    subpaths: { "./Generate": ["PROD-SBOM-001"] },
  },
  "effect-build-windows": {
    rootNamespaces: ["SignMsix"],
    subpaths: { "./SignMsix": ["PROD-WINDOWS-001"] },
  },
};

export const providerSurfaceSupport = {
  Api: { runtime: [], declarations: [] },
  Command: { runtime: ["layer"], declarations: ["LayerError", "LayerOptions", "layer"] },
};
