// Provider runtime code is projected from the validated contract. This template
// owns only release-number mechanics; banner decoding and relations stay local.
const scalarFunctions = String.raw`
export interface ReleaseVersion {
  readonly major: number;
  readonly minor: number;
  readonly patch: number;
}

export interface PatchWindow {
  readonly major: number;
  readonly minor: number;
  readonly fromPatch: number;
  readonly beforePatch: number | null;
}

export interface CommandPolicy {
  readonly key: string;
  readonly range: string;
  readonly accepts: readonly PatchWindow[];
  readonly rationale?: string;
}

export const parseReleaseVersion = (version: string): ReleaseVersion | undefined => {
  const match = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/u.exec(version);
  if (match === null || match[0] !== version) return undefined;
  const major = Number(match[1]);
  const minor = Number(match[2]);
  const patch = Number(match[3]);
  return [major, minor, patch].every(Number.isSafeInteger) ? { major, minor, patch } : undefined;
};

export const acceptsRelease = (
  policy: CommandPolicy,
  version: ReleaseVersion | undefined,
  channel: string,
): boolean =>
  version !== undefined
  && (channel === "unreported" || channel === "stable" || channel === "release")
  && policy.accepts.some((window) =>
    version.major === window.major && version.minor === window.minor && version.patch >= window.fromPatch
    && (window.beforePatch === null || version.patch < window.beforePatch)
  );

export const explainRefusal = (policy: CommandPolicy, version: string, channel: string): string => {
  const identity = JSON.stringify(version);
  const reason = parseReleaseVersion(version) === undefined
    ? "requires a canonical stable release version; prereleases and decorated identities are not admitted"
    : channel !== "unreported" && channel !== "stable" && channel !== "release"
    ? "reported channel is not admitted"
    : "version is outside the reviewed operation policy";
  return identity + " (channel " + channel + "): " + reason + "; accepted " + policy.range
    + (policy.rationale === undefined ? "" : ". " + policy.rationale);
};
`;

export const renderCompatibilityModule = (policies) => {
  const declarations = policies.map((policy, index) =>
    `const policy${index}: CommandPolicy = {
  key: ${JSON.stringify(policy.key)},
  range: ${JSON.stringify(policy.range)},
${policy.rationale === undefined ? "" : `  rationale:\n    ${JSON.stringify(policy.rationale)},\n`}  accepts: [
${
      policy.accepts.map((window) =>
        `    { major: ${window.major}, minor: ${window.minor}, fromPatch: ${window.fromPatch}, beforePatch: ${window.beforePatch} },`
      ).join("\n")
    }
  ],
};`
  ).join("\n\n");
  const bindings = policies.flatMap((policy, index) =>
    Object.keys(policy.operations).map((operation) => `  ${operation}: policy${index},`)
  );
  return `// Generated by scripts/effect-build-contract/generate.mjs. Do not edit.
import type { CommandOperation } from "./CommandError.js";
${scalarFunctions}
${declarations}

export const compatibilityByOperation = {
${bindings.join("\n")}
} as const satisfies Readonly<Record<Exclude<CommandOperation, "probe">, CommandPolicy>>;
`;
};

const table = (headers, rows) => {
  const widths = headers.map((header, index) => Math.max(header.length, ...rows.map((row) => row[index].length)));
  const row = (cells) => `| ${cells.map((cell, index) => cell.padEnd(widths[index])).join(" | ")} |`;
  return [row(headers), row(widths.map((width) => "-".repeat(width))), ...rows.map(row)].join("\n");
};

const renderDocumentation = (contract) => {
  const policies = contract.commandCompatibilityRegister.policies;
  const fixtures = contract.exactToolEvidenceRegister.tools.filter((tool) => tool.lane === "Command");
  const rows = policies.map((policy) => [
    policy.provider,
    policy.visibility,
    Object.keys(policy.operations).map((operation) => `\`${operation}\``).join(", "),
    // Pipes inside code spans still need escaping in Markdown tables.
    `\`${policy.range.replaceAll("|", "\\|")}\``,
  ]);
  return `# Compiler compatibility

<!-- Generated by scripts/effect-build-contract/generate.mjs. Do not edit. -->

Command admission is a maintained policy for the selected external compiler. Exact executable identity is recorded and reauthenticated before launch. No compiler is installed or substituted by the library.

${table(["Compiler", "Visibility", "Command operations", "Accepted releases"], rows)}

Private operations remain private; these rows do not add exports. Bun host APIs retain their exact 1.3.14 declaration/runtime boundary, and esbuild's supplied API package retains its exact native-service pairing. See [the option and target audit](provider-compatibility-audit.md) for the floors, exclusions, and evidence limits.

## Exact integration fixtures

These are pinned test inputs, not proof that every version in an accepted range was executed. A successful CI run establishes the specific versions, hosts, operations, and targets it actually ran.

${
    table(
      ["Fixture", "Compiler", "Version", "Expectation", "Operations"],
      fixtures.map((fixture) => [
        fixture.id,
        fixture.name,
        fixture.version,
        fixture.expectation ?? "admitted",
        fixture.operations.map((operation) => `\`${operation}\``).join(", "),
      ]),
    )
  }

Stable patches inside an admitted window run without an effect-build update. New minor lines require review. Users may pin exact compilers for reproducibility. Fixture updates select the newest available patch deliberately and remain exact in CI; when minimum and newest coincide, one fixture suffices. A discovered incompatible patch needs a regression test and a policy change. Installed effect-build releases cannot acquire a new exclusion without an update.

Unknown, prerelease, canary, malformed, or unreviewed decorated identities are refused. Unsupported-operation errors name the observed version and usable range. Identity probes do not claim that build, watch, or compile capabilities were executed.
`;
};

export const renderProjections = (contract) => {
  const policies = contract.commandCompatibilityRegister.policies;
  return new Map([
    ["tooling/effect-build-contract.json", `${JSON.stringify(contract, null, 2)}\n`],
    ...[...new Set(policies.map((policy) => policy.provider))].sort().map((provider) => [
      `packages/effect-build-${provider}/src/internal/Compatibility.generated.ts`,
      renderCompatibilityModule(policies.filter((policy) => policy.provider === provider)),
    ]),
    ["docs/compiler-compatibility.md", renderDocumentation(contract)],
  ]);
};
