export const mechanismFamilies = Object.freeze([
  ["direct-host-api", "official function, callback, or scoped handle in the provider's supported host"],
  ["selected-command", "one-shot or scoped provider command with native argv/project/process semantics"],
  ["official-language-library", "official Go or Rust library API outside the TypeScript host"],
  ["native-bridge", "supported or owned C/C++/N-API/FFI bridge"],
  ["embedded-engine", "linked or vendored upstream compiler/runtime core"],
  ["runtime-hosted-sidecar", "provider-native public API behind an effect-build-owned framed protocol"],
  ["persistent-session", "versioned daemon/service session with lifetime-bound handles"],
  ["wasm-worker", "supported WebAssembly, WASI, or provider worker boundary"],
  ["inverted-plugin", "provider owns execution and calls effect-build-controlled hooks/modules"],
  ["declarative-artifact", "stable config, manifest, project, or intermediate artifact handoff"],
  ["isolated-worker", "local/remote isolated worker used specifically for host or fault isolation"],
  ["upstream-contribution", "missing supported protocol/library/cancellation/event surface proposed upstream"],
]);

// The current TypeScript trace is deliberately hand-audited rather than
// inferred from mechanism templates. Bind its complete reviewed contents so a
// semantic cell cannot drift while retaining only the same surface names.
export const currentTsTraceSha256 = "354e0b3d4683ee23164c7731ce9b562ec7a8cc392700698d5d95b3776b6bca8d";

const op = (id, provider, operation, status, versions, evidence, recommendation, semantics = {}) => Object.freeze({
  id,
  provider,
  operation,
  status,
  versions,
  evidence,
  recommendation,
  ...semantics,
});

export const operations = Object.freeze([
  op("BUN-TRANSPILE-SYNC", "bun", "transpile source synchronously", "upstream operation; not frozen for 0.4", "1.3.9; comparative source 1.3.14", "Bun bun.d.ts:2350-2411 and JSTranspiler.zig:815-918 @ cf6cdbb", "direct-host-api in Bun; caller-thread blocking is part of the contract", { lifetimeDetail: "the native host form blocks its caller and exposes no cancellation handle; alternate boundaries must state any different isolation law", outputDetail: "caller-owned transformed source value" }),
  op("BUN-TRANSPILE-ASYNC", "bun", "transpile source asynchronously", "upstream operation; not frozen for 0.4", "1.3.9; comparative source 1.3.14", "Bun transpiler.mdx:71-93 and bun.d.ts:2350-2411 @ cf6cdbb", "direct-host-api; runtime-hosted-sidecar only for a non-Bun orchestrator", { lifetimeDetail: "one invocation with no provider-owned per-call cancellation handle; an isolating boundary must state its kill and outcome law", outputDetail: "caller-owned transformed source value" }),
  op("BUN-SCAN", "bun", "scan exports/imports and fast imports", "upstream operation; not frozen for 0.4", "1.3.9; comparative probe 1.3.14", "Bun bun.d.ts:2350-2411 @ cf6cdbb", "direct-host-api; bounded sidecar for serializable batching"),
  op("BUN-BUILD-MEMORY", "bun", "build/bundle with structured in-memory outputs and virtual files", "upstream operation; not frozen for 0.4", "1.3.9", "Bun bundler docs:295-335 and BuildConfig.files @ cf6cdbb", "direct-host-api; bounded sidecar when host independence matters"),
  op("BUN-BUILD-DISK-ASSETS", "bun", "direct multi-entry JS/CSS/HTML/assets build", "v0.3 borrowed single-main wrapper exists; broader operation not frozen", "1.3.9", "Bun bundler docs:155-173,295-335 @ cf6cdbb; Bundle.ts:366-463", "direct-host-api or selected-command according to authority; never claim multi-output transactionality"),
  op("BUN-PLUGINS-VIRTUAL", "bun", "plugins, macros, virtual inputs, native onBeforeParse", "upstream operation; not frozen for 0.4", "1.3.9", "Bun plugin docs:314-336 and bundle_v2.zig:2340-2354 @ cf6cdbb", "direct-host-api; provider-side selected module only as an explicit trust contract"),
  op("BUN-COMPILE-SCALAR", "bun", "compile one executable", "CAN-BUN-012 frozen for 0.4", "selected tool 1.3.9", "Adapter.ts:74-114; CompilerEngine.ts:386-457; SURFACE.json", "selected-command with Effect staging/publication", { lifetimeDetail: "one owned invocation and one private candidate must remain scoped until validation or cleanup", outputDetail: "one validated atomic-published executable" }),
  op("BUN-COMPILE-MATRIX", "bun", "compile a homogeneous-provider executable matrix", "derived operation frozen for 0.4", "selected tool 1.3.9", "CompilerEngine.ts:459-501; SURFACE.json derivedOperations", "repeated selected-command scalar cells under bounded Effect concurrency", { lifetimeDetail: "independent scalar cells; interruption closes active cells but does not roll back completed cells", outputDetail: "partial-success report; successful atomic publications survive failures in other cells" }),
  op("BUN-WATCH", "bun", "watch/rebuild", "upstream command only; not frozen", "1.3.9", "Bun bundler docs:147-153 @ cf6cdbb; issue 5866", "selected-command raw process until upstream exposes a typed context"),

  op("DENO-TRANSPILE", "deno", "transpile source without declaration emission", "experimental command; not frozen", "2.9.3", "Deno cli/lib.rs:216-223 and transpile.rs:107-174 @ f39575e", "selected-command for project-aware transpilation; deno_ast only for a distinct pure transform"),
  op("DENO-BUNDLE-MEMORY", "deno", "structured in-memory bundle", "experimental upstream operation; not frozen", "2.9.3; comparative R2 2.9.5", "Deno lib.deno.unstable.d.ts:11-199 and provider.rs:119-184 @ f39575e", "direct Deno.bundle or bounded selected-Deno sidecar; explicitly experimental"),
  op("DENO-BUNDLE-STDOUT", "deno", "bundle to stdout", "experimental upstream operation; not frozen", "2.9.3", "Deno cli/lib.rs:159-165 and bundle/mod.rs @ f39575e", "selected-command with bounded stdout collection and native project authority", { outputDetail: "caller-owned collected bytes; no durable publication" }),
  op("DENO-BUNDLE-DISK", "deno", "bundle directly to disk with multi-output assets", "experimental upstream operation; not frozen", "2.9.3", "Deno cli/lib.rs:159-165 and bundle/mod.rs @ f39575e", "selected-command for native project authority; provider-direct multi-output mutation", { outputDetail: "provider-direct durable output graph; no transactionality claim" }),
  op("DENO-CHECK", "deno", "type-check a bundle/project", "not frozen", "2.9.3", "Deno bundle/mod.rs:306-395 @ f39575e", "selected-command; host bundle API explicitly disables checking", { outputDetail: "diagnostics and success/failure, not declaration files" }),
  op("DENO-DECLARATIONS", "deno", "emit declarations while transpiling", "not frozen", "2.9.3", "Deno transpile.rs:236-331 @ f39575e", "selected-command with native project/type-checker authority", { outputDetail: "provider-direct declaration/source-map output set" }),
  op("DENO-PROJECT-AUTHORITY", "deno", "deno.json/workspace/import-map/lock/environment/permissions", "authority dimension used by provider operations", "2.9.3", "Deno exact CLI flags/config source @ f39575e", "selected-command plus native declarative project files"),
  op("DENO-COMPILE-SCALAR", "deno", "compile one executable", "CAN-DENO-010 frozen for 0.4", "deno and denort 2.9.3", "Adapter.ts:168-205; compile.rs:189-218,713-799; CompilerEngine.ts:386-457; SURFACE.json", "selected-command with Effect staging/publication", { lifetimeDetail: "one owned invocation and one private candidate must remain scoped until validation or cleanup; provider acquisition/cache effects may outlive failure", outputDetail: "one validated atomic-published executable; provider cache mutation may survive" }),
  op("DENO-COMPILE-MATRIX", "deno", "compile a homogeneous-provider executable matrix", "derived operation frozen for 0.4", "deno and denort 2.9.3", "CompilerEngine.ts:459-501; SURFACE.json derivedOperations", "repeated selected-command scalar cells under bounded Effect concurrency", { lifetimeDetail: "independent scalar cells/acquisitions; interruption closes active cells without implying rollback", outputDetail: "partial-success report; successful publications and provider cache mutations are not rolled back" }),
  op("DENO-RUNTIME-ACQUISITION", "deno", "target denort acquisition and target binding", "part of compile, not a separate public operation", "deno/denort 2.9.3", "Deno standalone/binary.rs:376-435,502-538 @ f39575e", "leave under selected Deno authority; observe cache/network mutation"),
  op("DENO-WATCH", "deno", "bundle/compile watch and private rebuild context", "command process only; not frozen", "2.9.3", "Deno bundle/mod.rs:1066-1167 and compile.rs:42-67 @ f39575e", "selected-command raw session; typed session is upstream-dependent"),

  op("ESB-TRANSFORM", "esbuild", "transform source", "upstream operation; not frozen", "0.28.2", "esbuild pkg/api/api.go:474-488 and lib/npm/node.ts @ 609683d", "official JavaScript API; Go API only for a Go consumer", { outputDetail: "caller-owned code/map/warnings result" }),
  op("ESB-FORMAT-MESSAGES", "esbuild", "format structured messages", "upstream operation; not frozen", "0.28.2", "esbuild pkg/api/api.go:715-729 and service.go @ 609683d", "official JavaScript API; pure structured result", { outputDetail: "caller-owned formatted string array" }),
  op("ESB-ANALYZE-METAFILE", "esbuild", "analyze a metafile", "upstream operation; not frozen", "0.28.2", "esbuild pkg/api/api.go:731-746 and service.go @ 609683d", "official JavaScript API; pure structured result", { outputDetail: "caller-owned analysis string" }),
  op("ESB-BUILD-MEMORY", "esbuild", "build with structured in-memory outputs", "CAN-ESB-001 frozen for 0.4", "0.28.2", "esbuild API docs; common.ts protocol; SURFACE.json", "official JavaScript API over package-owned native service child"),
  op("ESB-BUILD-DIRECT", "esbuild", "provider-direct output writes", "upstream operation; explicit mutation mode", "0.28.2", "esbuild API write option and service.go @ 609683d", "JavaScript API or CLI; keep distinct from atomic publication"),
  op("ESB-PLUGINS-VIRTUAL", "esbuild", "plugins, virtual inputs, reverse callbacks", "upstream operation; not separately frozen", "0.28.2", "esbuild common.ts:1169-1240 @ 609683d", "official JavaScript API; callback RPC sidecars rejected absent a concrete need"),
  op("ESB-CONTEXT-REBUILD", "esbuild", "create a context and rebuild", "CAN-ESB-011 frozen for 0.4", "0.28.2", "esbuild API docs and pkg/api/api.go:529-560; SURFACE.json", "official JavaScript context scoped by Effect; package-module-global child is not scoped", { lifetimeDetail: "long-lived context handle whose cancel/dispose law and underlying executor ownership must both be explicit", outputDetail: "caller-owned in-memory BuildResult per rebuild" }),
  op("ESB-WATCH", "esbuild", "start context watch", "method of CAN-ESB-011; not an independent frozen root", "0.28.2", "esbuild API docs and service.go @ 609683d; SURFACE.json", "official JavaScript context for acknowledgement and plugin onEnd results; CLI only for raw process semantics", { lifetimeDetail: "watch lives until context disposal; no independent stop method", outputDetail: "acknowledgement only; plugin onEnd is the native result channel" }),
  op("ESB-SERVE", "esbuild", "start context serve", "method of CAN-ESB-011; not an independent frozen root", "0.28.2", "esbuild API docs and service.go @ 609683d; SURFACE.json", "official JavaScript context; network authority ends at context disposal", { lifetimeDetail: "server lives until context disposal", outputDetail: "caller-owned port/hosts result plus provider-owned listening socket" }),
  op("ESB-CANCEL", "esbuild", "cancel an active context build", "method of CAN-ESB-011", "0.28.2", "esbuild API docs, common.ts, service.go @ 609683d; SURFACE.json", "official JavaScript context cancel; does not dispose the context", { lifetimeDetail: "waits for the active build/callback path to settle; later rebuild remains valid", outputDetail: "completion acknowledgement; active rebuild rejects as canceled" }),
  op("ESB-DISPOSE", "esbuild", "dispose a context", "hidden Scope-owned release of CAN-ESB-011", "0.28.2", "esbuild API docs, common.ts, service.go @ 609683d; SURFACE.json", "official JavaScript context dispose owned by an uninterruptible Scope finalizer", { lifetimeDetail: "idempotently invalidates the context; the underlying executor may have a wider lifetime and must not be falsely claimed as released", outputDetail: "release acknowledgement; no build artifact" }),

  op("NODE-DIRECT-SEA", "node-sea", "direct SEA generation", "CAN-NODE-001 frozen for 0.4", "Node 26.7.0", "Node SEA docs:21-137 and node_sea_bin.cc:380-480 @ b4f23d3; NodeSea.ts:671-728", "selected exact Node --build-sea with private candidate and atomic publication", { mechanismOverrides: { "declarative-artifact": { selectedIdentity: "medium-base-selected-builder-companion-selected" } } }),
  op("NODE-LEGACY-BLOB", "node-sea", "legacy preparation-blob generation", "documented verification flow; not frozen", "Node 26.7.0", "Node SEA docs:495-625 @ b4f23d3", "selected exact Node command; blob remains exact-version private artifact"),
  op("NODE-LEGACY-INJECT", "node-sea", "inject a legacy preparation blob", "not frozen", "Node 26.7.0; postject 1.0.0-alpha.6", "nodejs/postject api.js:1-163 @ 3c4f208 and Node SEA docs", "pinned postject programmatic adapter only if legacy injection becomes required", { lifetimeDetail: "one injection attempt against a private candidate; the boundary must state whether work is non-cancellable in-process or kill-isolated with outcome-unknown mutation", outputDetail: "provider-direct in-place mutation; caller must validate before publication" }),
  op("NODE-CANDIDATE-REPAIR", "node-sea", "repair platform metadata after SEA mutation", "platform operation; not frozen", "Node 26.7.0", "Node SEA docs and node_sea_bin.cc @ b4f23d3", "explicit selected-command platform capability on a private candidate; never a hidden fallback", { authorityDetail: "platform repair tool owns metadata mutation; effect-build retains candidate/publication ownership", outputDetail: "mutated private candidate only", mechanismOverrides: { "selected-command": { helped: true, caller: "explicit platform repair command", execution: "selected local platform-tool child", transport: "argv, terminal streams, private candidate filesystem mutation", availability: "platform-specific public tool; no portable Node-owned repair API", authority: "caller selects tool and private candidate; effect-build owns later validation/publication", inputs: "private mutated candidate and explicit repair policy", lifetime: "one-shot scoped child", outputs: "mutated private candidate only", distribution: "platform toolchain required on artifact host", compatibility: "platform format/tool/version specific", fit: "candidate repair after a named mutation only", nonFit: "not SEA generation and never an automatic fallback", complexity: "adds one explicit post-mutation platform stage", verdict: "viable only when a target requires repair" } } }),
  op("NODE-SIGN", "node-sea", "sign a mutated SEA candidate", "distribution operation; not frozen", "Node 26.7.0 plus platform signer", "Node SEA docs signing guidance @ b4f23d3", "explicit selected-command platform signer after mutation and before publication", { authorityDetail: "caller/platform selects signing identity and credentials", outputDetail: "signed private candidate, then caller validation/publication", mechanismOverrides: { "selected-command": { helped: true, caller: "explicit signer command", execution: "selected local signing child", transport: "argv, credential/keychain authority, terminal streams, private candidate mutation", availability: "documented platform signing tools; outside Node SEA API", authority: "caller selects signer, identity, credentials, and candidate", inputs: "private mutated executable plus signing policy/identity", lifetime: "one-shot scoped child; credential prompts must not be inferred", outputs: "signed private candidate followed by validation/publication", distribution: "target-platform signer and credentials required", compatibility: "platform signature format and toolchain", fit: "post-mutation signing only", nonFit: "not SEA generation/injection and never a hidden fallback", complexity: "separate security-sensitive platform stage", verdict: "viable when distribution policy requires signing" } } }),
  op("NODE-MAIN-ASSETS", "node-sea", "main/assets ingestion", "main/assets subset used by v0.3/freeze", "Node 26.7.0", "Node SEA docs and node_sea.cc:723-792 @ b4f23d3", "official SEA config consumed by selected command", { mechanismOverrides: { "declarative-artifact": { selectedIdentity: "medium-base-selected-builder-companion-selected" } } }),
  op("NODE-SNAPSHOT-CACHE-ARGS", "node-sea", "code cache, snapshot, exec arguments", "upstream fields; cache/snapshot intentionally disabled by freeze", "Node 26.7.0", "Node SEA docs:21-137 and node_sea.cc @ b4f23d3", "selected command/config; keep cross-target constraints explicit", { mechanismOverrides: { "declarative-artifact": { selectedIdentity: "medium-base-selected-builder-companion-selected" } } }),
  op("NODE-RUNTIME-SEA", "node-sea", "runtime node:sea asset/identity API", "artifact-runtime operation, not build lane", "Node 26.7.0", "Node SEA docs:294-493 @ b4f23d3", "runtime-api inside produced executable", { mechanismOverrides: { "direct-host-api": { selectedIdentity: "high-content-bound-runtime" }, "declarative-artifact": { selectedIdentity: "high-content-bound-runtime" } } }),
  op("NODE-EMBEDDER-SNAPSHOT", "node-sea", "C++ embedder and generic snapshot products", "distinct product; not SEA", "Node 26.7.0", "Node embedding docs and node.h:460-484,946-994 @ b4f23d3", "reject as SEA alternative"),

  op("ROLL-BUILD-MEMORY", "rolldown", "generate in-memory output", "R6 package deferred", "1.2.4", "rolldown-build.ts:23-147 and classic_bundler.rs:1-48 @ 483c648", "direct JavaScript/N-API only after package admission gates"),
  op("ROLL-WRITE", "rolldown", "provider-direct multi-output write", "R6 package deferred", "1.2.4", "binding_bundler.rs and CLI bundle.ts @ 483c648", "direct JavaScript/N-API or selected CLI after admission; no transactionality claim"),
  op("ROLL-PLUGINS", "rolldown", "plugins and virtual inputs", "R6 package deferred", "1.2.4", "plugin API and bindingify-plugin.ts @ 483c648", "direct JavaScript/N-API; JSON sidecar is not faithful"),
  op("ROLL-LIFECYCLE", "rolldown", "generate/write/close and native external-memory ownership", "R6 package deferred; in-flight close law fails", "1.2.4", "external-memory-handle.ts and freeze R6 verdict", "no admission until wrapper joins in-flight work and materializes/releases native outputs"),
  op("ROLL-WATCH-DEV", "rolldown", "watch/dev/incremental engine", "experimental and R6 deferred", "1.2.4", "packages/rolldown/src/api/dev/dev-engine.ts:21-129,151-178 @ 483c648", "upstream-dependent plus package gates; do not infer incrementality from RolldownBuild"),
]);

const commonEffect = "Reuse Effect Scope for owned handles/children, ChildProcess for selected processes, FileSystem/Path for explicit mutation, Stream only for a real typed event source, Layer for selection and dependency provision, and preserve Cause interruption.";

const mechanism = ({
  helped = [], adjunct = [], implementation = [], caller, execution, transport, direction = "effect-build calls provider", availability,
  authority, inputs, lifetime, outputs, distribution, compatibility, fit, nonFit, complexity,
  verdict, confidence = "high", effect = commonEffect, selectedIdentity,
}) => Object.freeze({
  helped: Object.freeze(helped), adjunct: Object.freeze(adjunct), implementation: Object.freeze(implementation),
  caller, execution, transport, direction, availability, authority,
  inputs, lifetime, outputs, distribution, compatibility, fit, nonFit, complexity, effect, verdict, confidence,
  selectedIdentity,
});

const negative = (availability, nonFit, complexity, confidence = "high") => mechanism({
  caller: "none supported", execution: "not available as a supported provider surface", transport: "none",
  availability, authority: "would require effect-build to own an unsupported engine/ABI or substitute semantics",
  inputs: "no supported faithful request/result boundary", lifetime: "unproven", outputs: "unproven",
  distribution: "would require new native/source distribution", compatibility: "unsupported coupling",
  fit: "none", nonFit, complexity, verdict: "reject", confidence,
});

export const providerMechanisms = Object.freeze({
  bun: Object.freeze({
    "direct-host-api": mechanism({ helped:["BUN-TRANSPILE-SYNC","BUN-TRANSPILE-ASYNC","BUN-SCAN","BUN-BUILD-MEMORY","BUN-BUILD-DISK-ASSETS","BUN-PLUGINS-VIRTUAL"], caller:"function/value/plugin callback", execution:"Bun isolate -> Zig binding -> caller thread for sync transpile/scan or singleton native bundle thread/work pool for Bun.build", transport:"direct JS/native binding", availability:"documented public Bun 1.3.9 API, host-restricted, MIT plus bundled component licenses", authority:"ambient Bun host selects runtime/engine; request selects config/targets; host cwd/env apply", inputs:"retains closures, plugin objects, virtual files, blobs, structured logs and BuildArtifact bytes", lifetime:"Transpiler is caller-owned; Bun.build is one-shot over hidden shared threads and exposes no cancel/context", outputs:"borrowed/in-memory blobs or provider-direct files; compile may mutate an outfile", distribution:"requires Bun host and exact supported host/platform binary", compatibility:"public Bun API/version; no independent engine handshake", fit:"highest fidelity for Bun-native host operations and callbacks", nonFit:"does not preserve the frozen compile operation's layer-selected command identity, CLI project/default authority, or publication law; exposes no typed build watch context", complexity:"few adapter concepts; ambient identity and non-cancellable native work remain", verdict:"viable now for host-API operations" }),
    "selected-command": mechanism({ helped:["BUN-BUILD-DISK-ASSETS","BUN-COMPILE-SCALAR","BUN-COMPILE-MATRIX","BUN-WATCH"], caller:"command/config", execution:"selected local Bun child", transport:"argv, terminal byte streams, filesystem", availability:"documented public Bun 1.3.9 CLI, MIT plus bundled component licenses", authority:"explicit/PATH selected binary; CLI owns project/config/env/target and possible runtime acquisition", inputs:"preserves native project/config/flags; loses arbitrary JS closures and structured result objects", lifetime:"one-shot child or raw watch process; Scope can kill process but does not invent provider cancellation", outputs:"provider-direct files; effect-build compile wraps one file in private staging/atomic rename", distribution:"release binary per host; cross-target compile may acquire target runtime", compatibility:"probe exact version/path/capability; terminal diagnostics are not typed machine events", fit:"best for compile and process/project-authority operations", nonFit:"not equivalent to structured memory/virtual/plugin APIs", complexity:"reuses Effect process/lifecycle and adds no owned protocol", verdict:"viable now" }),
    "official-language-library": negative("no supported non-JavaScript Bun compiler library found at bun-v1.3.9 after public docs/declarations/source-tree search", "no Bun operation has an official Go/Rust/C library boundary", "a new language library would be upstream work or a fork"),
    "native-bridge": negative("no supported outward Bun compiler C ABI/N-API/FFI surface found at bun-v1.3.9; native onBeforeParse is a narrow plugin hook", "FFI and Node-API load user code into Bun and do not expose Bun's compiler to another host", "per-platform ABI/safety/certification; not a small general bridge"),
    "embedded-engine": negative("Bun compiler internals are source-visible but unsupported for embedding at cf6cdbb", "would couple to Bun/JSC/Zig internals instead of a supported operation", "12k+ blobs, Zig/JSC toolchain, large build/distribution and LGPL component obligations"),
    "runtime-hosted-sidecar": mechanism({ helped:["BUN-TRANSPILE-ASYNC","BUN-SCAN","BUN-BUILD-MEMORY"], caller:"framed request/result", execution:"explicit Bun child calling public Bun API", transport:"effect-build-owned length-framed pipe/socket protocol", availability:"effect-build-owned prototype over documented public Bun API; not an upstream protocol", authority:"effect-build selects binary/digest/protocol; provider process owns Bun engine/cwd/env", inputs:"faithful only for serializable source/options/bytes; plugin closures require selected provider-side code and cannot be JSON values", lifetime:"one-shot or persistent process; request IDs, queue bounds, handshake, kill, restart and stale handles are adapter-owned", outputs:"structured bytes may cross with copies; direct files mutate sidecar namespace; publication remains effect-build-owned", distribution:"requires Bun binary on every provider host and protocol server source", compatibility:"exact version/capability/digest handshake required", fit:"useful only when host independence exposes structured Bun semantics unavailable to a Node orchestrator", nonFit:"cannot preserve synchronous caller-thread blocking or the frozen compile operation's selected-command/project/publication law, and arbitrary plugins/watch do not cross faithfully", complexity:"adds protocol/session/crash/copy states; removes host-runtime coupling for serializable operations", verdict:"viable with bounded package-private adapter", confidence:"medium-high" }),
    "persistent-session": mechanism({ helped:["BUN-TRANSPILE-ASYNC","BUN-SCAN"], caller:"session plus reusable transpiler handle", execution:"persistent Bun sidecar; native transpiler calls inside it", transport:"framed RPC with generation-bound IDs", availability:"effect-build prototype only; no upstream Bun session protocol", authority:"selected sidecar owns engine; caller owns handle lifecycle", inputs:"serializable source/options/results; no closure transfer", lifetime:"explicit handshake/create/use/close/shutdown; crash invalidates every generation handle", outputs:"in-memory copied results", distribution:"Bun plus owned server on each platform", compatibility:"protocol and Bun capabilities negotiated", fit:"batching can reuse configured Transpiler and amortize startup", nonFit:"cannot preserve synchronous caller-thread blocking; Bun.build exposes no reusable context and executable compile has no session value", complexity:"queue/backpressure/stale-handle/idle-memory/restart states added", verdict:"research-only unless batching demand is concrete", confidence:"medium" }),
    "wasm-worker": negative("no supported Bun compiler WASM/WASI build or executable WASM target found at bun-v1.3.9; Bun Worker is experimental and still Bun-hosted", "does not improve host independence or preserve build/watch semantics", "worker termination/structured-clone states without a supported portable engine"),
    "inverted-plugin": mechanism({ helped:["BUN-PLUGINS-VIRTUAL"], caller:"provider-loaded plugin/module", execution:"Bun owns bundle threads and calls JS/native hooks", transport:"direct callbacks inside Bun or explicitly selected provider-side module", availability:"documented public plugin API; native onBeforeParse is narrow and platform-restricted", authority:"provider process controls schedule; caller/plugin controls hook code and mutable closure state", inputs:"preserves virtual modules and callbacks only when code runs inside Bun", lifetime:"plugin callback/reentrancy lifetime tied to build; no general cancellation", outputs:"plugin may alter module/output graph; direct writes remain provider mutation", distribution:"plugin code/native addon must be installed and trusted in provider host", compatibility:"Bun plugin API plus module/native ABI", fit:"truthful for the exact plugin/virtual-input operation", nonFit:"a callback is an adjunct, not the build/compile/transpiler caller surface; loading code is not serializing a callback", complexity:"adds code-mobility/trust/reentrancy identity", verdict:"viable now only as provider-native direct integration" }),
    "declarative-artifact": mechanism({ helped:[], caller:"project/config files plus command/API request", execution:"Bun host/child consumes native files", transport:"filesystem artifact handoff", availability:"documented bunfig/tsconfig/package inputs, but no standalone stable build manifest or compiler IR", authority:"project retains native configuration authority", selectedIdentity:"low-artifact-does-not-select-runtime", inputs:"configuration survives; virtual bytes/callbacks/handles/diagnostics do not", lifetime:"one-shot adjunct to API/command", outputs:"not an independent build result protocol", distribution:"ordinary project files", compatibility:"provider config version", fit:"preserve project authority only as an adjunct", nonFit:"config does not execute or produce any inventoried operation; a file containing argv is still CLI semantics", complexity:"low as adjunct; invalid if promoted as independent engine protocol", verdict:"adjunct only, never a standalone operation mechanism" }),
    "isolated-worker": negative("a Bun Worker or remote worker can be built but no operation requires it beyond the sidecar case", "same-host worker keeps Bun dependence; remote execution is explicitly out of scope", "duplicates sidecar authority and adds trust/transport/workspace state"),
    "upstream-contribution": mechanism({ helped:["BUN-TRANSPILE-SYNC","BUN-TRANSPILE-ASYNC","BUN-SCAN","BUN-BUILD-MEMORY","BUN-BUILD-DISK-ASSETS","BUN-PLUGINS-VIRTUAL","BUN-COMPILE-SCALAR","BUN-COMPILE-MATRIX","BUN-WATCH"], caller:"future supported handle/protocol/library", execution:"chosen by Bun", transport:"future versioned ABI/protocol/events", availability:"hypothetical and unproven; issue 5866 covers build watch API need", authority:"must expose exact engine/capability identity", inputs:"should preserve structured results/plugins or explicitly exclude them", lifetime:"needs AbortSignal/cancel and context/rebuild/dispose laws", outputs:"must distinguish bytes, direct mutation, and publication", distribution:"upstream-owned releases", compatibility:"documented version/capability contract", fit:"would change current negatives if shipped and supported", nonFit:"not usable now", complexity:"moves compatibility burden upstream but still needs adapter certification", verdict:"upstream-dependent" }),
  }),

  deno: Object.freeze({
    "direct-host-api": mechanism({ helped:["DENO-BUNDLE-MEMORY","DENO-BUNDLE-DISK","DENO-PROJECT-AUTHORITY"], caller:"experimental Deno.bundle function", execution:"Deno isolate -> Rust op -> fresh OS thread/current-thread Tokio -> esbuild 0.25.5 service child per call", transport:"direct runtime op then internal framed stdio to esbuild", availability:"documented public experimental Deno 2.9.3 API requiring unstable bundle, MIT", authority:"ambient Deno launch flags/cwd/config/permissions are cloned; private provider selects esbuild helper", inputs:"structured output bytes; no public plugins, virtual map, check/declarations, watch, or session", lifetime:"one-shot call; no public cancel/context and inner child is recreated", outputs:"structured bytes or provider-direct writes", distribution:"requires Deno host; may acquire internal esbuild package", compatibility:"experimental API and hidden helper identity", fit:"structured experimental bundle inside a Deno host", nonFit:"does not implement the exact stdout command-stream contract and cannot implement compile/check/declarations/session semantics", complexity:"low caller code but hidden thread/child/acquisition and no cancellation", verdict:"viable only as experimental host-restricted operation" }),
    "selected-command": mechanism({ helped:["DENO-TRANSPILE","DENO-BUNDLE-STDOUT","DENO-BUNDLE-DISK","DENO-CHECK","DENO-DECLARATIONS","DENO-PROJECT-AUTHORITY","DENO-COMPILE-SCALAR","DENO-COMPILE-MATRIX","DENO-RUNTIME-ACQUISITION","DENO-WATCH"], caller:"command/config/project", execution:"selected local Deno child; bundle may spawn esbuild; compile may acquire denort", transport:"argv, terminal streams, filesystem/network/cache", availability:"documented public Deno 2.9.3 CLI; bundle/transpile and compile --bundle are experimental where marked, MIT", authority:"explicit/PATH selected Deno owns config/import-map/lock/permissions/env/targets and acquisition", inputs:"highest native project authority; terminal diagnostics not stable typed events", lifetime:"one-shot or raw watch process; Effect owns child scope only", outputs:"stdout/direct files; effect-build compile adds private staging and atomic publication", distribution:"Deno plus denort/esbuild acquisition/caches according to operation", compatibility:"probe exact path/version/capability; selected Deno and denort must align", fit:"only truthful current compile/check/declaration/watch mechanism", nonFit:"does not yield Deno.bundle structured results or plugin callbacks", complexity:"reuses process/file capabilities; cache/network mutation remains provider-owned", verdict:"viable now" }),
    "official-language-library": mechanism({ helped:[], caller:"Rust deno_ast functions", execution:"caller Rust process", transport:"direct Rust calls", availability:"Deno-owned deno_ast 0.53.3, MIT, explicit non-SemVer support posture", authority:"Rust dependency selects parser/transpiler; caller must supply options", inputs:"pure per-file parse/transpile only; no project graph/config/import map/permissions/check/declarations", lifetime:"one-shot Rust values", outputs:"in-memory transformed source", distribution:"Rust toolchain and native dependencies", compatibility:"exact crate coupling", fit:"a distinct narrow pure-transform product only", nonFit:"the inventoried DENO-TRANSPILE operation retains Deno project authority; deno_ast does not", complexity:"new Rust bridge/toolchain for a deliberately narrower product", verdict:"not viable for the inventoried operations", confidence:"medium-high" }),
    "native-bridge": negative("no supported Deno bundle/compile C ABI, N-API, or FFI surface found at v2.9.3", "a bridge over private CLI crates would inherit exact-source/V8 coupling", "native V8 and per-platform bridge distribution"),
    "embedded-engine": negative("deno_core 0.408.0 and deno_runtime 0.263.0 are runtime embedding products; private CLI bundle/compile modules are highly unstable", "they do not expose Deno's required bundle/check/compile operations; deno_bundle_runtime asks the embedder to provide an engine", "exact workspace/V8/source lockstep, broad resolver/runtime graph, maintained fork"),
    "runtime-hosted-sidecar": mechanism({ helped:["DENO-BUNDLE-MEMORY"], caller:"framed request/result", execution:"selected Deno child calls public runtime API", transport:"effect-build-owned framed pipe/socket protocol", availability:"effect-build-owned design over experimental Deno APIs; no upstream machine protocol", authority:"explicit Deno version/path/capabilities plus explicit cwd/config/import-map/lock/permissions", inputs:"structured serializable bytes/options; no callbacks/session/check/declarations beyond public API", lifetime:"process can persist, but each Deno.bundle call still creates a thread and esbuild child", outputs:"bytes cross with copies; direct-write mode mutates provider filesystem", distribution:"Deno binary plus server source", compatibility:"exact protocol/runtime/capability handshake", fit:"host-independent access to structured experimental Deno.bundle", nonFit:"Deno exposes no public project-transpile runtime API; compile/transpile sidecars would merely wrap CLI, and persistence does not reuse the inner engine", complexity:"adds protocol/process while preserving only a narrow experimental gain", verdict:"viable with bounded package-private adapter", confidence:"medium" }),
    "persistent-session": negative("Deno.bundle exposes no reusable handle and recreates its inner service; CLI watch's context is private", "a daemon cannot truthfully claim incremental state for the public API", "session IDs/backpressure/crash/idle state without reusable provider state"),
    "wasm-worker": negative("no supported Deno CLI bundle/compile WASM/WASI engine surface found at v2.9.3", "deno_core/deno_runtime embedding and esbuild helper are not a portable Deno build API", "V8/runtime/permissions/filesystem capability loss"),
    "inverted-plugin": negative("deno_bundle_runtime exposes a BundleProvider hook, but the embedder must supply a different engine; Deno's CliBundleProvider is private", "does not expose Deno's own bundler or preserve its project semantics", "would substitute an engine and duplicate Deno resolution/config logic"),
    "declarative-artifact": mechanism({ helped:[], adjunct:["DENO-PROJECT-AUTHORITY"], caller:"deno.json/workspace/import map/lock plus command", execution:"selected Deno consumes canonical project files", transport:"filesystem/project handoff", availability:"documented public Deno project/config surface", authority:"project files and permission flags remain canonical rather than flattened into generic options", selectedIdentity:"low-artifact-does-not-select-runtime", inputs:"preserves scopes/imports/locks/compile includes; does not itself execute", lifetime:"durable project state consumed per command", outputs:"configuration only; private eszip/standalone formats are not stable interchange", distribution:"ordinary source/project artifacts", compatibility:"Deno config schema/version", fit:"required adjunct for the exact project-authority operation", nonFit:"config alone does not execute bundle/check/declaration/compile/acquisition operations", complexity:"reduces duplicated normalization when kept native", verdict:"viable adjunct, not a standalone operation mechanism" }),
    "isolated-worker": negative("local/remote worker adds no semantics beyond an explicit Deno sidecar or selected command", "remote build infrastructure is outside scope and local isolation is already a child", "workspace/security/transport/outcome-unknown states"),
    "upstream-contribution": mechanism({ helped:["DENO-TRANSPILE","DENO-BUNDLE-MEMORY","DENO-BUNDLE-STDOUT","DENO-BUNDLE-DISK","DENO-CHECK","DENO-DECLARATIONS","DENO-PROJECT-AUTHORITY","DENO-COMPILE-SCALAR","DENO-COMPILE-MATRIX","DENO-RUNTIME-ACQUISITION","DENO-WATCH"], caller:"future stable Rust API or machine service/context", execution:"Deno-owned", transport:"versioned protocol/library and typed event stream", availability:"hypothetical; plugin request 32157 is unaccepted", authority:"must expose runtime/helper/config/permission/target identities", inputs:"structured outputs/plugins/check/declarations according to explicit capabilities", lifetime:"needs rebuild/cancel/dispose and acquisition outcome laws", outputs:"must distinguish bytes/direct write/standalone publication", distribution:"upstream-owned platform artifacts", compatibility:"stable version/capability contract", fit:"would change bounded negatives", nonFit:"not usable now", complexity:"moves private CLI coupling upstream", verdict:"upstream-dependent" }),
  }),

  esbuild: Object.freeze({
    "direct-host-api": mechanism({ helped:["ESB-TRANSFORM","ESB-FORMAT-MESSAGES","ESB-ANALYZE-METAFILE","ESB-BUILD-MEMORY","ESB-BUILD-DIRECT","ESB-PLUGINS-VIRTUAL","ESB-CONTEXT-REBUILD","ESB-CANCEL","ESB-DISPOSE","ESB-WATCH","ESB-SERVE"], caller:"official JavaScript functions and context handle", execution:"Node host plus one package-module-global native esbuild child per resolved module instance; sync calls use a worker-owned child", transport:"private framed bidirectional stdio hidden behind supported JS API", availability:"documented public esbuild 0.28.2 JS API, MIT; service protocol is undocumented internal", authority:"the installed package normally resolves its matching optional platform binary, but ambient ESBUILD_BINARY_PATH can override that path; cwd/env are inherited", inputs:"full structured results/options/virtual inputs and host plugin closures through reverse callbacks", lifetime:"one-shot operations through one module instance share its service; contexts expose rebuild/watch/serve/cancel/dispose; that module instance's global stop affects its consumers", outputs:"in-memory bytes or provider-direct files", distribution:"npm package plus platform binary or explicit ambient override; offline only when the selected bytes already exist", compatibility:"private first-packet exact-version check rejects version skew but does not content-bind an override; public compatibility is package API only", fit:"best TypeScript boundary for structured/plugin/context operations", nonFit:"binary identity is normally package resolution but can be ambient override, not caller-layer selected identity; direct writes are not atomic publication", complexity:"low adapter cost but ambient override authority, package-module-global crash/stop, and one-shot cancellation need explicit treatment", verdict:"viable now" }),
    "selected-command": mechanism({ helped:["ESB-BUILD-DIRECT"], caller:"command", execution:"selected native esbuild child", transport:"argv/stdin/stdout/stderr/filesystem", availability:"documented public esbuild 0.28.2 CLI, MIT", authority:"caller selects exact executable/cwd/env/flags", inputs:"native CLI options/project streams; no JS/Go plugin closures or structured API handles/results", lifetime:"one-shot or raw process-owned watch/serve; kill is the process boundary", outputs:"stdout/direct files", distribution:"single native platform binary", compatibility:"version/capability probe; terminal prose is not typed protocol", fit:"provider-direct build output when selected command/process semantics are the contract", nonFit:"structured transform/code-map-warning results, formatMessages, analyzeMetafile, plugins, virtual callbacks, reusable contexts, typed watch events, and structured ServeResult", complexity:"simple and well isolated", verdict:"viable now only for the exact command/direct-output contract" }),
    "official-language-library": mechanism({ helped:["ESB-TRANSFORM","ESB-FORMAT-MESSAGES","ESB-ANALYZE-METAFILE","ESB-BUILD-DIRECT"], caller:"official Go pkg/api functions and BuildContext", execution:"compiler linked directly in caller Go process", transport:"direct Go calls/callbacks", availability:"documented public official Go API at 0.28.2, MIT", authority:"Go module selects exact engine; caller owns options/filesystem/network", inputs:"Go-native options/results/plugins/contexts; serializable pure/direct-write operations retain provider semantics, while JS closures and JS context identity do not", lifetime:"Go contexts expose rebuild/watch/serve/cancel/dispose but are not JS context handles", outputs:"Go byte slices or provider-direct files", distribution:"requires Go application/toolchain build per target; no child binary at runtime", compatibility:"Go module SemVer/API", fit:"exact provider semantics for pure serializable calls/direct writes in a Go consumer", nonFit:"does not preserve frozen JS BuildOptions/BuildResult plugin closures or JS context handles; a TypeScript caller needs a separately evaluated bridge/sidecar", complexity:"low in Go; high if effect-build owns cross-language bridge", verdict:"viable now in Go; bounded adapter only for TypeScript" }),
    "native-bridge": negative("no supported esbuild C/C++/N-API/FFI ABI found at 0.28.2 after official docs/pkg/lib/cmd/manifests search", "an owned bridge would wrap Go internals rather than an upstream ABI", "per-platform ABI/build/signing and callback marshalling"),
    "embedded-engine": mechanism({ helped:["ESB-TRANSFORM","ESB-FORMAT-MESSAGES","ESB-ANALYZE-METAFILE","ESB-BUILD-DIRECT"], caller:"linked Go library", execution:"same Go process", transport:"direct Go calls", availability:"supported only through official Go API; vendoring internals beyond pkg/api is unsupported", authority:"Go module/build selects engine", inputs:"Go-native values; does not preserve JS closure/context identity", lifetime:"Go-native calls and contexts", outputs:"bytes/direct writes", distribution:"Go binary per platform", compatibility:"public Go API only", fit:"truthful embedded mechanism for pure/direct-write operations in Go applications", nonFit:"frozen JS build/plugin/context operations are not directly callable from TypeScript without another bridge", complexity:"reasonable in Go, substantial for this JS package train", verdict:"official for Go consumer; research-only for effect-build" }),
    "runtime-hosted-sidecar": mechanism({ helped:["ESB-TRANSFORM","ESB-FORMAT-MESSAGES","ESB-ANALYZE-METAFILE"], caller:"framed request/result", execution:"owned Go or Node sidecar invoking public API", transport:"effect-build protocol, possibly bidirectional", availability:"hypothetical/bounded adapter; not upstream", authority:"effect-build selects/distributes sidecar engine image and protocol", inputs:"serializable options/results; JS plugins need reverse callback RPC or provider-side module loading", lifetime:"one-shot or process session; context IDs require crash/stale-handle laws", outputs:"bytes copied over transport or files in sidecar namespace", distribution:"new binaries/server per platform", compatibility:"owned schema/handshake plus esbuild version", fit:"can give host independence/fault ownership for pure serializable operations", nonFit:"cannot preserve the frozen full BuildOptions/BuildResult plugin surface without an unproven callback protocol; duplicates the official JS package service", complexity:"protocol/platform packaging/callback/backpressure/session states added", verdict:"viable with bounded adapter for pure calls but no current simplification", confidence:"medium" }),
    "persistent-session": mechanism({ helped:["ESB-PLUGINS-VIRTUAL","ESB-CONTEXT-REBUILD","ESB-CANCEL","ESB-DISPOSE","ESB-WATCH","ESB-SERVE"], caller:"official JS service plus context handles, or owned session", execution:"shared native child for JS API; Go context for Go API", transport:"private service protocol behind public API", availability:"public contexts are supported; native service protocol is not", authority:"package-selected service; context owns build key while service is global", inputs:"full semantics through public API; do not expose private handle IDs", lifetime:"cancel/dispose are per context; stop/crash is global and invalidates every context", outputs:"structured/direct according to request", distribution:"normal esbuild package", compatibility:"exact internal handshake owned by upstream package", fit:"use public contexts directly where reusable state is the operation", nonFit:"one-shot build calls do not expose a caller-owned session; do not wrap them in a new daemon or use global stop as a per-scope finalizer", complexity:"reuses upstream session; effect-build only adds Scope law", verdict:"viable now through public contexts" }),
    "wasm-worker": mechanism({ helped:["ESB-TRANSFORM","ESB-FORMAT-MESSAGES","ESB-ANALYZE-METAFILE","ESB-PLUGINS-VIRTUAL"], caller:"browser JS API", execution:"Web Worker by default or same browser thread -> Go WASM service", transport:"postMessage/in-memory framed channel and WASM calls", availability:"documented public esbuild-wasm 0.28.2 browser API, MIT", authority:"caller selects exact wasmURL/module; no native selected binary", inputs:"in-memory/virtual/plugin inputs and structured results; no native filesystem", lifetime:"worker initialized/stopped; public support excludes sync/context/watch/serve", outputs:"in-memory bytes only; copies across worker/WASM", distribution:"WASM plus JS glue/browser worker; larger/slower than native", compatibility:"exact JS/WASM package version", fit:"browser-hosted transform/format/analyze/plugin semantics in the reduced domain", nonFit:"not the frozen installed-library/native-service full build operation; excludes direct writes, supported context/watch/serve, sync API, native performance/identity", complexity:"portable distribution but capability and copy/performance losses", verdict:"viable in reduced domain; research-only for effect-build" }),
    "inverted-plugin": mechanism({ helped:["ESB-PLUGINS-VIRTUAL"], caller:"plugin callbacks registered with public JS/Go API", execution:"native engine reverse-calls host callback", transport:"upstream bidirectional service callbacks or direct Go calls", availability:"documented public plugin API", authority:"engine owns schedule; host owns plugin code/state", inputs:"faithfully preserves closures, virtual modules, diagnostics and reentrancy in supported host", lifetime:"callbacks/build keys tied to build/context; cancellation waits on running host callbacks", outputs:"plugins can alter graph/results/direct writes", distribution:"plugin code installed with host", compatibility:"public plugin API and host runtime", fit:"faithful boundary for the exact plugin/virtual-input operation", nonFit:"a callback is an adjunct to builds and contexts, not the caller surface for build, rebuild, cancel, dispose, watch, or serve", complexity:"upstream already owns callback protocol; effect-build should not recreate it", verdict:"viable now through the direct API for plugin operations" }),
    "declarative-artifact": negative("esbuild intentionally exposes CLI flags/API objects and no native stable project config/IR interchange", "a JSON options file or stored argv does not change execution semantics and cannot contain callbacks", "parallel schema/config version without capability gain"),
    "isolated-worker": negative("a Node worker/remote worker can wrap the JS package, but the compiler is already in a child and no current operation needs remote infrastructure", "does not remove global service unless it becomes an owned sidecar and loses callbacks without code mobility", "duplicate process/protocol/security/workspace states"),
    "upstream-contribution": mechanism({ helped:["ESB-TRANSFORM","ESB-FORMAT-MESSAGES","ESB-ANALYZE-METAFILE","ESB-BUILD-MEMORY","ESB-BUILD-DIRECT","ESB-PLUGINS-VIRTUAL","ESB-CONTEXT-REBUILD","ESB-CANCEL","ESB-DISPOSE","ESB-WATCH","ESB-SERVE"], caller:"future supported service protocol/per-context service/cancel", execution:"upstream-defined", transport:"documented versioned protocol or additional public API", availability:"hypothetical; current --service is hidden/internal", authority:"would need explicit binary/service identity", inputs:"should preserve structured values and callback policy", lifetime:"per-operation cancel and crash recovery without global stop would change costs", outputs:"must retain direct/memory distinctions", distribution:"upstream-owned", compatibility:"documented protocol/version", fit:"would make an owned cross-host service much cheaper", nonFit:"not usable now", complexity:"upstream absorbs protocol maintenance", verdict:"upstream-dependent" }),
  }),

  "node-sea": Object.freeze({
    "direct-host-api": mechanism({ helped:["NODE-RUNTIME-SEA"], caller:"node:sea runtime functions", execution:"inside produced SEA artifact at runtime", transport:"direct built-in calls", availability:"documented public experimental Node 26.7.0 runtime API, Stability 1.1, MIT", authority:"built artifact/base determines runtime", inputs:"asset keys/bytes/borrowed raw asset memory", lifetime:"artifact process lifetime", outputs:"copies/blobs or borrowed executable memory", distribution:"inside exact SEA runtime", compatibility:"Node SEA runtime contract", fit:"runtime inspection/assets only", nonFit:"no supported JS assembly function exists", complexity:"no build adapter impact", verdict:"viable runtime contract" }),
    "selected-command": mechanism({ helped:["NODE-DIRECT-SEA","NODE-LEGACY-BLOB","NODE-MAIN-ASSETS","NODE-SNAPSHOT-CACHE-ARGS"], caller:"SEA config plus command", execution:"selected exact Node child running native LIEF builder/blob generator", transport:"argv, JSON config, terminal streams, filesystem", availability:"documented public experimental Node 26.7.0 SEA surface, Stability 1.1, MIT", authority:"explicit selected builder/base/cwd/config/target; current effect-build intentionally uses same selected path for builder and base", inputs:"native main/assets/snapshot/cache/args fields; terminal failures are not typed", lifetime:"one-shot scoped child; provider directly truncates/writes private candidate", outputs:"private blob or executable; effect-build validates and atomically publishes final candidate", distribution:"exact Node binary with LIEF per target; post-mutation signing may be required", compatibility:"exact builder/base version, target and snapshot/cache restrictions", fit:"preferred direct and legacy-blob mechanism", nonFit:"does not expose programmatic typed assembly or callbacks", complexity:"smallest supported direct route; Effect staging removes Node writer's unsafe destination mutation", verdict:"viable now" }),
    "official-language-library": negative("no supported official Node SEA library API found at v26.7.0; public C++ embedder is a distinct runtime product", "cannot assemble/inject SEA through an official language library", "would require Node internal linkage or another injector"),
    "native-bridge": mechanism({ helped:["NODE-LEGACY-INJECT"], caller:"postject.inject Promise API", execution:"same Node isolate plus bundled LIEF/Emscripten Wasm", transport:"direct JS/Wasm calls and filesystem paths", availability:"supported external nodejs/postject 1.0.0-alpha.6, MIT; LIEF Apache-2.0; prerelease/no declarations", authority:"package selects injector/LIEF independently; caller selects base/blob/resource/fuse", inputs:"Buffer blob and options; structured Error only, no AbortSignal", lifetime:"one-shot Promise; interruption cannot stop Wasm or later write", outputs:"whole executable rebuilt and mutated in place; copies across JS/C++/Wasm", distribution:"Node package/Wasm; independently certify every format/Node/LIEF combination", compatibility:"alpha API and Node SEA resource/fuse; postject LIEF 0.13 differs from Node 26.7 LIEF 0.17", fit:"genuine programmatic legacy injection", nonFit:"does not generate direct SEA/blob and is not a C ABI for Node SEA", complexity:"adds injector/version/LIEF/mutation axis", verdict:"viable with bounded package-private adapter only if legacy injection is required", confidence:"medium-high" }),
    "embedded-engine": negative("Node C++ embedder/snapshot APIs are public but do not produce SEA; node::sea assembly symbols are internal under NODE_WANT_INTERNALS", "generic embedded Node or snapshot lacks NODE_SEA_BLOB/fuse/node:sea semantics", "building/distributing Node,V8,libuv,OpenSSL,ICU,LIEF per target and exact ABI/source lockstep"),
    "runtime-hosted-sidecar": mechanism({ helped:["NODE-LEGACY-INJECT"], caller:"framed injection request", execution:"selected Node child calls pinned postject API", transport:"owned RPC plus filesystem", availability:"bounded effect-build adapter over third-party alpha API", authority:"effect-build selects Node/postject/protocol; request selects private candidate/blob", inputs:"serializable paths/bytes/options; machine failure envelope", lifetime:"one-shot process can be killed for fault isolation; crash during write yields outcome unknown on private candidate", outputs:"private candidate mutation followed by caller validation/publication", distribution:"Node+postject server per platform", compatibility:"Node/postject/capability handshake", fit:"only when orchestrator host cannot load postject or kill isolation is required", nonFit:"wrapping node --build-sea is merely CLI RPC and a daemon has no reusable engine", complexity:"protocol/cold Node+Wasm/copy/crash states", verdict:"viable bounded adapter for legacy injection only", confidence:"medium" }),
    "persistent-session": negative("postject creates its Wasm module per call and Node SEA exposes no reusable assembly context", "no reusable provider state to amortize; direct builder is one-shot", "adds stale handles/backpressure/restart/idle memory without semantic gain"),
    "wasm-worker": mechanism({ helped:[], implementation:["NODE-LEGACY-INJECT"], caller:"postject JS API backed by Wasm", execution:"Node process Emscripten/LIEF Wasm", transport:"JS buffers/filesystem into Wasm", availability:"supported only as part of postject alpha.6 Node package; no browser/WASI standalone builder found", authority:"postject package internally selects Wasm/LIEF; effect-build cannot select it independently", inputs:"blob/base buffers copied; Node fs/path/Buffer required", lifetime:"one-shot module/no cancel", outputs:"in-place file mutation", distribution:"Node-only supported wrapper, 256MiB initial/4GiB max Wasm memory configuration", compatibility:"alpha package and exact SEA resource contract", fit:"implementation dependency beneath the public postject injection route", nonFit:"not an independently callable browser/WASI/worker or direct SEA engine", complexity:"large memory/copy and mutation costs", verdict:"implementation detail only; use public postject API if admitted" }),
    "inverted-plugin": negative("no Node SEA build-time plugin/hook/callback surface found at v26.7.0", "runtime module loading occurs after artifact startup and is not assembly", "invented hooks would require a custom builder/fork"),
    "declarative-artifact": mechanism({ helped:[], adjunct:["NODE-DIRECT-SEA","NODE-LEGACY-BLOB","NODE-LEGACY-INJECT","NODE-MAIN-ASSETS","NODE-SNAPSHOT-CACHE-ARGS","NODE-RUNTIME-SEA"], caller:"official sea-config plus preparation blob/final resource", execution:"selected Node or postject consumes config/blob; final runtime consumes NODE_SEA_BLOB", transport:"filesystem JSON and binary resource handoff", availability:"documented Stability-1.1 config/blob/runtime layout; blob encoding itself is not versioned portable schema", authority:"config explicitly binds main/base/output/options/assets; resource name/fuse bind legacy injection and runtime", selectedIdentity:"low-artifact-does-not-select-builder-or-runtime", inputs:"retains native fields; unknown config fields currently ignored", lifetime:"one-shot config/private blob; durable final executable/resource", outputs:"private blob and durable runtime resource; final publication remains caller-owned", distribution:"ordinary config/blob plus exact Node/base; platform signing after mutation", compatibility:"exact Node version/target/fuse; snapshot/cache host restrictions", fit:"required declarative adjunct to selected Node, postject injection, and the final node:sea runtime", nonFit:"config/artifact alone is not the build, injector, or runtime engine; preparation blob is not a cross-version ABI", complexity:"reduces argv field explosion but requires exact identity/validation", verdict:"viable now as an adjunct to the selected primary route" }),
    "isolated-worker": negative("remote/local isolation is useful only for target-native signing/launch or a postject sidecar already covered", "direct Node child already provides fault isolation; remote infrastructure is out of scope", "workspace/credentials/signing/outcome protocol burden"),
    "upstream-contribution": mechanism({ helped:["NODE-DIRECT-SEA","NODE-LEGACY-BLOB","NODE-LEGACY-INJECT","NODE-MAIN-ASSETS","NODE-SNAPSHOT-CACHE-ARGS"], caller:"future structured SEA builder/blob API", execution:"Node-owned library/process", transport:"typed function or documented machine protocol", availability:"hypothetical; current internal BuildSingleExecutable is unsupported", authority:"should expose builder/base/LIEF/target capabilities", inputs:"all config fields with schema validation and typed errors", lifetime:"cancellation or bytes-returning ownership would remove outcome-unknown writes", outputs:"prefer injectBytes/buildBytes or explicit private outfile", distribution:"official Node releases/libnode if supported", compatibility:"versioned schema/API/ABI", fit:"would reopen direct programmatic assembly", nonFit:"not usable now", complexity:"moves internal coupling upstream", verdict:"upstream-dependent" }),
  }),

  rolldown: Object.freeze({
    "direct-host-api": mechanism({ helped:["ROLL-BUILD-MEMORY","ROLL-WRITE","ROLL-PLUGINS","ROLL-LIFECYCLE","ROLL-WATCH-DEV"], caller:"public JavaScript functions, build/watch handles and plugin callbacks", execution:"host process -> package N-API addon -> Rust/Tokio threads", transport:"JS/N-API callbacks and native-backed objects", availability:"documented public Rolldown 1.2.4 JS API; build/watch experimental; MIT; entire provider deferred by freeze", authority:"package/native addon/host graph selects engine; caller owns config/plugins", inputs:"rich closures, virtual inputs, structured diagnostics and lazy external native memory", lifetime:"build handle exposes generate/write/close but full builds are fresh; watch/dev experimental; close in-flight law currently fails freeze", outputs:"native-backed lazy in-memory outputs or provider-direct files", distribution:"Node engine declared; platform N-API packages/WASI fallback", compatibility:"package/addon/host relation; override path can evade exact version enforcement", fit:"truthful upstream mechanism after admission gates", nonFit:"not currently an effect-build surface and not proven portable/incremental", complexity:"low wrapper shape but native faults/external-memory/close races require ownership law", verdict:"upstream viable; effect-build deferred" }),
    "selected-command": mechanism({ helped:["ROLL-WRITE"], caller:"Node shebang CLI/config module", execution:"selected Node -> rolldown JS -> N-API addon/Rust threads", transport:"argv, executable JS/TS config, terminal streams/filesystem", availability:"documented public Rolldown 1.2.4 CLI, MIT; provider deferred", authority:"PATH selects Node and script/package graph rather than standalone Rust binary", selectedIdentity:"medium-relational-node-package-addon-graph", inputs:"native config modules may load plugins; terminal output loses structured JS results and handle methods", lifetime:"one-shot or raw watcher process", outputs:"stdout/direct files", distribution:"Node plus JS package plus native addon", compatibility:"relational Node/package/addon identity", fit:"provider-direct write semantics after admission", nonFit:"cannot return the exact in-memory output objects or expose the combined watch/dev engine handle operation", complexity:"more identity axes than a standalone CLI", verdict:"research-only while provider deferred" }),
    "official-language-library": mechanism({ helped:["ROLL-BUILD-MEMORY","ROLL-WRITE"], caller:"published Rust rolldown crate", execution:"caller Rust process", transport:"direct Rust calls/traits", availability:"official public crate 1.2.4, MIT, but upstream explicitly promises no SemVer/docs/team support", authority:"Cargo graph selects exact engine", inputs:"Rust-native options/results; Rust plugin traits do not preserve JavaScript closures", lifetime:"Rust engine-specific", outputs:"native Rust values/direct files", distribution:"Rust toolchain/binary per target", compatibility:"exact-source coupling despite published crate", fit:"mechanically exposes build/write engine operations to a Rust consumer", nonFit:"does not preserve the inventoried JS plugin, wrapper external-memory/close, or package DevEngine/watch operations and is not a supportable stable effect-build boundary", complexity:"very high source maintenance and platform build burden", verdict:"research-only" }),
    "native-bridge": mechanism({ helped:[], implementation:["ROLL-BUILD-MEMORY","ROLL-WRITE","ROLL-PLUGINS","ROLL-LIFECYCLE","ROLL-WATCH-DEV"], caller:"package JavaScript API", execution:"same-process package-owned N-API addon and Tokio runtime", transport:"N-API plus callbacks/lazy external memory", availability:"source-visible package binding shipped by Rolldown, not a general supported ABI", authority:"package binding loader selects platform addon/WASI", inputs:"full JS adapter semantics including callbacks", lifetime:"native runtime holder/build/output memory", outputs:"lazy native-backed output or direct files", distribution:"platform .node optional packages", compatibility:"N-API host plus package/addon version relation", fit:"implementation below the public JS API", nonFit:"not an independently supported architecture; a second custom bridge is redundant and no general C ABI exists", complexity:"upstream absorbs bridge; effect-build must still certify memory/lifecycle", verdict:"implementation detail only; use through public JS API after admission" }),
    "embedded-engine": negative("Rolldown Rust crate is published but explicitly unsupported for SemVer/docs/team support; binding crate is publish=false", "embedding would bind effect-build to fast-moving Rust internals", "native toolchain/platform/source lockstep and plugin ABI maintenance", "high"),
    "runtime-hosted-sidecar": mechanism({ helped:["ROLL-BUILD-MEMORY","ROLL-WRITE"], caller:"framed serializable request/result", execution:"Node/Rust sidecar loads Rolldown", transport:"owned RPC; output bytes eagerly copied", availability:"hypothetical effect-build adapter; provider remains deferred", authority:"sidecar selects package/addon/Rust engine", inputs:"serializable options/results only; plugin closures require code loading or bidirectional RPC", lifetime:"one-shot/session; crash invalidates handles; native outputs must be materialized/released", outputs:"copied bytes or sidecar filesystem mutation", distribution:"Node+N-API or Rust binaries across platforms", compatibility:"protocol plus package/addon/host handshake", fit:"fault isolation for plugin-free operations", nonFit:"does not solve package admission, callbacks, external memory or close race", complexity:"very high protocol/distribution/memory/callback state", verdict:"research-only/reject for current freeze" }),
    "persistent-session": negative("RolldownBuild repeats full builds; current close can resolve before in-flight generate; no cancellation", "session protocol would add opaque IDs without proven incremental state and worsen close/crash ownership", "stale handles, callback RPC, output release, backpressure, restart and in-flight join"),
    "wasm-worker": mechanism({ helped:[], caller:"package loader branch, if a compatible host selects it", execution:"source-visible WASI/N-API-RS fallback; runtime behavior not retained as checked evidence", transport:"JS/WASI bridge shape visible in source; callback and output parity unproven", availability:"source-visible fallback at Rolldown 1.2.4; experimental Node WASI behavior; MIT; provider deferred; no retained reproducible runtime probe", authority:"environment/package loader can select WASI/native fallback", inputs:"runtime inputs, JavaScript plugin callbacks, and parity are unproven", lifetime:"runtime handle, callback, and native-memory laws are unproven on this branch", outputs:"runtime output ownership/copy behavior is unproven", distribution:"WASI package plus compatible host support would be required", compatibility:"package/WASI/host capability relation is source-visible but uncertified", fit:"none established by durable evidence", nonFit:"does not close admission/lifecycle gates and has no retained proof of build or plugin parity", complexity:"additional fallback/capability/performance states", verdict:"source-visible hypothesis only; not viable on current evidence", confidence:"low" }),
    "inverted-plugin": mechanism({ helped:["ROLL-PLUGINS"], caller:"JavaScript plugin hooks", execution:"Rust engine calls host JS through N-API", transport:"direct async callbacks with PluginContext/output mutation", availability:"documented public plugin API at 1.2.4", authority:"engine owns schedule; host owns closure state/code", inputs:"full non-serializable closures/virtual inputs/mutation", lifetime:"hooks include closeBundle; tied to build/watcher", outputs:"plugin can mutate output and manage external resources", distribution:"plugin modules in host process", compatibility:"public JS plugin API", fit:"only faithful boundary for the exact plugin operation", nonFit:"callbacks are adjuncts and do not initiate build/write, own wrapper external-memory lifecycle, or create watch/dev handles", complexity:"reentrancy/concurrency/resource cleanup, but upstream owns mapping", verdict:"upstream viable for plugins; effect-build deferred" }),
    "declarative-artifact": negative("Rolldown config files are executable JS/TS and may export functions/plugins; no stable data-only build manifest/IR found", "storing argv/config path keeps CLI/package semantics and cannot represent closures", "parallel schema would lose native configuration"),
    "isolated-worker": negative("a worker/remote host could isolate N-API faults but no current admitted operation justifies the transport", "does not close lifecycle/package/callback/memory gates", "workspace/code-mobility/protocol/crash states"),
    "upstream-contribution": mechanism({ helped:["ROLL-BUILD-MEMORY","ROLL-WRITE","ROLL-PLUGINS","ROLL-LIFECYCLE","ROLL-WATCH-DEV"], caller:"future stable Rust/ABI or cancellable joined handle", execution:"Rolldown-owned", transport:"supported API/ABI", availability:"hypothetical", authority:"must expose package/native/host capability identity", inputs:"retain plugin/output ownership explicitly", lifetime:"cancel plus close-joins-in-flight law required", outputs:"stable eager/borrowed memory semantics required", distribution:"upstream platform artifacts", compatibility:"SemVer/support promise", fit:"would reopen deferred mechanisms after all package gates", nonFit:"not usable now", complexity:"upstream absorbs fast-moving binding contract", verdict:"upstream-dependent" }),
  }),
});

export const architectureCandidates = Object.freeze([
  ["A", "current operation-specific hybrid", ["direct-host-api", "selected-command"]],
  ["B", "provider-host sidecars", ["runtime-hosted-sidecar"]],
  ["C", "persistent provider sessions", ["persistent-session"]],
  ["D", "embedded/native/WASM engines", ["official-language-library", "native-bridge", "embedded-engine", "wasm-worker"]],
  ["E", "inverted/declarative integration", ["inverted-plugin", "declarative-artifact"]],
  ["F", "operation-specific portfolio", mechanismFamilies.map(([id]) => id)],
]);

// Architecture F is deliberately explicit. Selecting the first mechanism that
// happens to list an operation as "helped" silently turns the portfolio back
// into a universal precedence rule and can contradict the operation verdict.
export const portfolioSelections = Object.freeze({
  "BUN-TRANSPILE-SYNC": ["direct-host-api"],
  "BUN-TRANSPILE-ASYNC": ["direct-host-api"],
  "BUN-SCAN": ["direct-host-api"],
  "BUN-BUILD-MEMORY": ["direct-host-api"],
  "BUN-BUILD-DISK-ASSETS": ["direct-host-api", "selected-command"],
  "BUN-PLUGINS-VIRTUAL": ["direct-host-api"],
  "BUN-COMPILE-SCALAR": ["selected-command"],
  "BUN-COMPILE-MATRIX": ["selected-command"],
  "BUN-WATCH": ["selected-command"],
  "DENO-TRANSPILE": ["selected-command"],
  "DENO-BUNDLE-MEMORY": ["direct-host-api"],
  "DENO-BUNDLE-STDOUT": ["selected-command"],
  "DENO-BUNDLE-DISK": ["selected-command"],
  "DENO-CHECK": ["selected-command"],
  "DENO-DECLARATIONS": ["selected-command"],
  "DENO-PROJECT-AUTHORITY": ["selected-command", "declarative-artifact"],
  "DENO-COMPILE-SCALAR": ["selected-command"],
  "DENO-COMPILE-MATRIX": ["selected-command"],
  "DENO-RUNTIME-ACQUISITION": ["selected-command"],
  "DENO-WATCH": ["selected-command"],
  "ESB-TRANSFORM": ["direct-host-api"],
  "ESB-FORMAT-MESSAGES": ["direct-host-api"],
  "ESB-ANALYZE-METAFILE": ["direct-host-api"],
  "ESB-BUILD-MEMORY": ["direct-host-api"],
  "ESB-BUILD-DIRECT": ["direct-host-api", "selected-command"],
  "ESB-PLUGINS-VIRTUAL": ["direct-host-api"],
  "ESB-CONTEXT-REBUILD": ["direct-host-api"],
  "ESB-CANCEL": ["direct-host-api"],
  "ESB-DISPOSE": ["direct-host-api"],
  "ESB-WATCH": ["direct-host-api"],
  "ESB-SERVE": ["direct-host-api"],
  "NODE-DIRECT-SEA": ["selected-command", "declarative-artifact"],
  "NODE-LEGACY-BLOB": ["selected-command", "declarative-artifact"],
  "NODE-LEGACY-INJECT": ["native-bridge", "declarative-artifact"],
  "NODE-CANDIDATE-REPAIR": ["selected-command"],
  "NODE-SIGN": ["selected-command"],
  "NODE-MAIN-ASSETS": ["selected-command", "declarative-artifact"],
  "NODE-SNAPSHOT-CACHE-ARGS": ["selected-command", "declarative-artifact"],
  "NODE-RUNTIME-SEA": ["direct-host-api", "declarative-artifact"],
  "NODE-EMBEDDER-SNAPSHOT": ["embedded-engine"],
  "ROLL-BUILD-MEMORY": ["direct-host-api"],
  "ROLL-WRITE": ["direct-host-api", "selected-command"],
  "ROLL-PLUGINS": ["direct-host-api"],
  "ROLL-LIFECYCLE": ["direct-host-api"],
  "ROLL-WATCH-DEV": ["direct-host-api"],
});

// This operation is intentionally represented by the rejected mechanism it
// must not be confused with; every other portfolio selection is faithful or a
// declared adjunct.
export const portfolioRejectedOperations = Object.freeze(["NODE-EMBEDDER-SNAPSHOT"]);

// Composite portfolios must distinguish alternative execution routes from
// required adjunct artifacts. A bare `+` cannot carry that authority fact.
export const portfolioRelations = Object.freeze({
  "BUN-BUILD-DISK-ASSETS": "alternative routes selected by output/project authority",
  "DENO-PROJECT-AUTHORITY": "selected command with native project artifacts as required adjuncts",
  "ESB-BUILD-DIRECT": "alternative API or command routes selected by caller contract",
  "NODE-DIRECT-SEA": "selected command consumes the documented config artifact",
  "NODE-LEGACY-BLOB": "selected command produces an exact-version private blob artifact",
  "NODE-LEGACY-INJECT": "postject injection consumes the exact preparation blob/resource-and-fuse artifact",
  "NODE-MAIN-ASSETS": "selected command consumes declarative main/assets fields",
  "NODE-SNAPSHOT-CACHE-ARGS": "selected command consumes declarative SEA feature fields",
  "NODE-RUNTIME-SEA": "the runtime API consumes the content-bound embedded NODE_SEA_BLOB/assets",
  "ROLL-WRITE": "deferred alternative API or command routes",
});
