import { Schema } from "effect";
import { Artifact } from "effect-build";
import type { AcceptedReference } from "./Notary.js";

export const App = Schema.Struct({ ...Artifact.Directory.fields, product: Schema.Literal("app") }).check(Schema.makeFilter((value) => Schema.is(Artifact.Directory)(value) ? undefined : "invalid directory artifact"));
export type App = typeof App.Type;
export const Dmg = Schema.Struct({ ...Artifact.File.fields, product: Schema.Literal("dmg") });
export type Dmg = typeof Dmg.Type;
export const Pkg = Schema.Struct({ ...Artifact.File.fields, product: Schema.Literal("pkg") });
export type Pkg = typeof Pkg.Type;
export const Product = Schema.Union([App, Dmg, Pkg]);
export type Product = typeof Product.Type;
const signature = { certificateSha1: Schema.String, secureTimestamp: Schema.Literal(true) };
export const SignedApp = Schema.Struct({ ...App.fields, signature: Schema.Struct({ ...signature, hardenedRuntime: Schema.Literal(true) }) }).check(Schema.makeFilter((value) => Schema.is(App)(value) ? undefined : "invalid app artifact"));
export type SignedApp = typeof SignedApp.Type;
export const SignedDmg = Schema.Struct({ ...Dmg.fields, signature: Schema.Struct(signature) });
export type SignedDmg = typeof SignedDmg.Type;
export const SignedPkg = Schema.Struct({ ...Pkg.fields, signature: Schema.Struct(signature) });
export type SignedPkg = typeof SignedPkg.Type;
export const SignedProduct = Schema.Union([SignedApp, SignedDmg, SignedPkg]);
export type SignedProduct = typeof SignedProduct.Type;
/** A standalone Mach-O executable signed with the hardened runtime; ZIP-notarizable, never stapled. */
export const SignedExecutable = Schema.Struct({ ...Artifact.Executable.fields, signature: Schema.Struct({ ...signature, hardenedRuntime: Schema.Literal(true) }) }).check(Schema.makeFilter((value) => Schema.is(Artifact.Executable)(value) ? undefined : "invalid executable artifact"));
export type SignedExecutable = typeof SignedExecutable.Type;
export const Signed = Schema.Union([SignedApp, SignedDmg, SignedPkg, SignedExecutable]);
export type Signed = typeof Signed.Type;
/** Explicit content identities for remote notarization and acceptance matching. */
export const HashedSignedApp = Schema.Struct({ ...SignedApp.fields, ...Artifact.HashedDirectory.fields }).check(Schema.makeFilter((value) => Schema.is(Artifact.HashedDirectory)(value) ? undefined : "invalid hashed app artifact"));
export type HashedSignedApp = typeof HashedSignedApp.Type;
export const HashedSignedDmg = Schema.Struct({ ...SignedDmg.fields, ...Artifact.HashedFile.fields });
export type HashedSignedDmg = typeof HashedSignedDmg.Type;
export const HashedSignedPkg = Schema.Struct({ ...SignedPkg.fields, ...Artifact.HashedFile.fields });
export type HashedSignedPkg = typeof HashedSignedPkg.Type;
export const HashedSignedExecutable = Schema.Struct({ ...SignedExecutable.fields, ...Artifact.HashedExecutable.fields }).check(Schema.makeFilter((value) => Schema.is(Artifact.HashedExecutable)(value) ? undefined : "invalid hashed executable artifact"));
export type HashedSignedExecutable = typeof HashedSignedExecutable.Type;
export const HashedSignedProduct = Schema.Union([HashedSignedApp, HashedSignedDmg, HashedSignedPkg]);
export type HashedSignedProduct = typeof HashedSignedProduct.Type;
export const HashedSigned = Schema.Union([HashedSignedApp, HashedSignedDmg, HashedSignedPkg, HashedSignedExecutable]);
export type HashedSigned = typeof HashedSigned.Type;
export type StapledApp = SignedApp & { readonly ticket: AcceptedReference };
export type StapledDmg = SignedDmg & { readonly ticket: AcceptedReference };
export type StapledPkg = SignedPkg & { readonly ticket: AcceptedReference };
export type StapledProduct = StapledApp | StapledDmg | StapledPkg;
