// Generated by scripts/effect-build-contract/generate.mjs. Do not edit.
import type { CommandOperation } from "./CommandError.js";

export interface ReleaseVersion {
  readonly major: number;
  readonly minor: number;
  readonly patch: number;
}

export interface PatchWindow {
  readonly major: number;
  readonly minor: number;
  readonly fromPatch: number;
  readonly beforePatch: number | null;
}

export interface CommandPolicy {
  readonly key: string;
  readonly range: string;
  readonly accepts: readonly PatchWindow[];
  readonly rationale?: string;
}

export const parseReleaseVersion = (version: string): ReleaseVersion | undefined => {
  const match = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/u.exec(version);
  if (match === null || match[0] !== version) return undefined;
  const major = Number(match[1]);
  const minor = Number(match[2]);
  const patch = Number(match[3]);
  return [major, minor, patch].every(Number.isSafeInteger) ? { major, minor, patch } : undefined;
};

export const acceptsRelease = (
  policy: CommandPolicy,
  version: ReleaseVersion | undefined,
  channel: string,
): boolean =>
  version !== undefined
  && (channel === "unreported" || channel === "stable" || channel === "release")
  && policy.accepts.some((window) =>
    version.major === window.major && version.minor === window.minor && version.patch >= window.fromPatch
    && (window.beforePatch === null || version.patch < window.beforePatch)
  );

export const explainRefusal = (policy: CommandPolicy, version: string, channel: string): string => {
  const identity = JSON.stringify(version);
  const reason = parseReleaseVersion(version) === undefined
    ? "requires a canonical stable release version; prereleases and decorated identities are not admitted"
    : channel !== "unreported" && channel !== "stable" && channel !== "release"
    ? "reported channel is not admitted"
    : "version is outside the reviewed operation policy";
  return identity + " (channel " + channel + "): " + reason + "; accepted " + policy.range
    + (policy.rationale === undefined ? "" : ". " + policy.rationale);
};

const policy0: CommandPolicy = {
  key: "deno-command-public:138e16439d828b49",
  range: "=2.9.5",
  rationale:
    "Deno 2.9.6 removed public transpile --conditions and compile --allow-scripts options. Admission stays at 2.9.5 until an upstream repair is reviewed.",
  accepts: [
    { major: 2, minor: 9, fromPatch: 5, beforePatch: 6 },
  ],
};

const policy1: CommandPolicy = {
  key: "deno-command-private:4a5e074b28ff982f",
  range: "=2.9.5",
  accepts: [
    { major: 2, minor: 9, fromPatch: 5, beforePatch: 6 },
  ],
};

export const compatibilityByOperation = {
  compileExecutable: policy0,
  transpileDeclarations: policy0,
  transpileDirect: policy0,
  transpileStdout: policy0,
  bundleDeclarations: policy1,
  bundleDirect: policy1,
  bundleStdout: policy1,
  bundleWatch: policy1,
  compileWatch: policy1,
} as const satisfies Readonly<Record<Exclude<CommandOperation, "probe">, CommandPolicy>>;
